---
permalink: windows/concept_collecting_additional_log_information_for_easier_debugging.html 
sidebar: sidebar 
keywords: collect, additional, log, information, debug, fail, external, environment 
summary: 失敗した SnapManager 処理をデバッグするために追加のログが必要な場合は、外部環境変数 server.log.level を設定する必要があります。この変数は、デフォルトのログレベルを上書きし、ログファイル内のすべてのログメッセージをダンプします。たとえば、ログレベルを DEBUG に変更できます。これにより、追加のメッセージが記録され、問題のデバッグに役立ちます。 
---
= デバッグを容易にするために追加のログ情報を収集する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
失敗した SnapManager 処理をデバッグするために追加のログが必要な場合は、外部環境変数 server.log.level を設定する必要があります。この変数は、デフォルトのログレベルを上書きし、ログファイル内のすべてのログメッセージをダンプします。たとえば、ログレベルを DEBUG に変更できます。これにより、追加のメッセージが記録され、問題のデバッグに役立ちます。

SnapManager ログは、次の場所にあります。

* SnapManager_install_directory\log


デフォルトのログレベルを上書きするには、次の手順を実行する必要があります。

. SnapManager のインストールディレクトリに platform.override テキストファイルを作成します。
. platform.override テキストファイルに server.log.level パラメータを追加します。
. 値（ trace 、 debug 、 Info 、 warn 、 error 、 FATAL （致命的）または progress （進行状況）を server.log.level パラメータに指定します。
+
たとえば、ログレベルを ERROR に変更するには、 server.log.level の値を error に設定します。

+
server.log.level= エラーです

. SnapManager サーバを再起動します。



NOTE: 追加のログ情報が不要な場合は、 platform.override テキストファイルから server.log.level パラメータを削除できます。

SnapManager は、 smo .config ファイルの次のパラメータのユーザ定義値に基づいて、サーバ・ログ・ファイルのボリュームを管理します。

* log.max_log_files
* log.max_log_file_size
* log.max_roling_operation_factory-logs

