---
permalink: windows/concept_advantages_of_using_snapmanager.html 
sidebar: sidebar 
keywords: oracle, task, database, manage, data, advantage 
summary: SnapManager for Oracle を使用すると、データベースに対してさまざまなタスクを実行し、データを効率的に管理できます。 
---
= SnapManager を使用する利点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager for Oracle を使用すると、データベースに対してさまざまなタスクを実行し、データを効率的に管理できます。

SnapManager for Oracle はストレージ・システムと連携し、次の作業を実行できます。

* プライマリストレージまたはセカンダリストレージへのスペース効率に優れたバックアップを作成し、バックアップをスケジュールします。
+
データベースのフルバックアップと部分バックアップを作成し、保持期間ポリシーを適用できます。 SnapManager （ 3.2 以降）では、データファイルとアーカイブログのバックアップのみを作成できます。

+
** SnapManager （ 3.2 以降）を使用すると、バックアップおよびリストア処理の前後に前処理または後処理を実行できます。
** SnapManager （ 3.2 以降）では、ポストプロセススクリプトを使用してバックアップを保護できます。


* ファイルベースのリストア処理を使用して、データベースの全体または一部をリストアします。
* データベースバックアップを自動的にリストアおよびリカバリする。
+
SnapManager （ 3.2 以降）を使用すると、データベース・バックアップのリストアとリカバリが自動的に実行されます。SnapManager は、アーカイブ・ログ・ファイルをバックアップから検出、マウント、および適用することにより、リストアされたデータベースを自動的にリカバリします。

* アーカイブログだけのバックアップを作成する場合は、アーカイブログデスティネーションからアーカイブログファイルを削除します。
* 一意のアーカイブログファイルがあるバックアップだけを保持することで、アーカイブログバックアップの最小数が自動的に保持されます。
* 処理の詳細を追跡し、ホスト、プロファイル、バックアップ、またはクローン別にレポートを生成できます。
* バックアップステータスを確認
* プロファイルに関連付けられた SnapManager 処理の履歴を保持します。
* プライマリストレージに、スペース効率に優れたバックアップのクローンを作成します。

