---
permalink: windows/concept_variables_available_in_the_task_scripts_for_backup_operation.html 
sidebar: sidebar 
keywords: provide, context, information, form, environment, variable, relate, backup, perform 
summary: SnapManager は、実行されるバックアップ処理に関連する環境変数の形式でコンテキスト情報を提供します。たとえば、元のホストの名前、保持ポリシーの名前、バックアップのラベルを取得できます。 
---
= バックアップ処理のタスクスクリプトで使用できる変数
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager は、実行されるバックアップ処理に関連する環境変数の形式でコンテキスト情報を提供します。たとえば、元のホストの名前、保持ポリシーの名前、バックアップのラベルを取得できます。

次の表に、スクリプトで使用できる環境変数を示します。

|===


| 変数（ variables ） | 説明 | の形式で入力し 


 a| 
sm_created
 a| 
現在の処理の ID を指定します
 a| 
文字列



 a| 
sm_created ：プロファイル名
 a| 
使用するプロファイルの名前を指定します
 a| 
文字列



 a| 
sm_created
 a| 
データベースのシステム識別子を指定します
 a| 
文字列



 a| 
sm_created
 a| 
データベースのホスト名を指定します
 a| 
文字列



 a| 
sm_created
 a| 
データベースのオペレーティングシステム（ OS ）の所有者を指定します
 a| 
文字列



 a| 
SM_OS_GROUP
 a| 
データベースの OS グループを指定します
 a| 
文字列



 a| 
sm_created タイプ
 a| 
バックアップのタイプを指定します（ online 、 offline 、 auto ）。
 a| 
文字列



 a| 
sm_created ：バックアップラベル
 a| 
バックアップのラベルを指定します
 a| 
文字列



 a| 
sm_created ：バックアップ ID
 a| 
バックアップの ID を指定します
 a| 
文字列



 a| 
sm_created 保持
 a| 
保持期間を指定します
 a| 
文字列



 a| 
sm_created
 a| 
このバックアップに使用するプロファイルを指定します
 a| 
文字列



 a| 
sm_created データベースのシャットダウン
 a| 
データベースを起動またはシャットダウンするかどうかを指定します必要に応じて ' コマンドラインインタフェースから -force オプションを使用できます
 a| 
ブール値



 a| 
sm_created スコープ
 a| 
バックアップの範囲を指定します（フルまたはパーシャル）。
 a| 
文字列



 a| 
sm_created ：ストレージシステム名
 a| 
ターゲットストレージシステム名を指定します。 * 注：複数のストレージシステムを使用する場合は、ストレージシステム名をカンマで区切って指定する必要があります。
 a| 
文字列



 a| 
sm_created ボリューム名を指定します
 a| 
ターゲットボリューム名を指定します。 * 注：ターゲットボリューム名には、ストレージデバイス名の先頭に sm_created というような名前を付ける必要があります。
 a| 
文字列



 a| 
SM_HOST_FILE_SYSTEM
 a| 
ホスト・ファイルシステムを指定します
 a| 
文字列



 a| 
sm_created 名前
 a| 
Snapshot リストを指定します。 * 注： Snapshot コピー名には、ストレージ・システム名およびボリューム名のプレフィックスを付ける必要があります。Snapshot コピーの名前はカンマで区切って指定します。
 a| 
文字列の配列



 a| 
sm_created ディレクトリ
 a| 
アーカイブログディレクトリを指定します。 * 注：アーカイブログが複数のディレクトリにある場合は、これらのディレクトリの名前をカンマで区切って指定します。
 a| 
文字列の配列



 a| 
sm_created ディレクトリ
 a| 
REDO ログディレクトリを指定します * 注： REDO ログが複数のディレクトリに格納されている場合、これらのディレクトリの名前はカンマで区切って指定します。
 a| 
文字列の配列



 a| 
sm_created ファイルディレクトリ
 a| 
制御ファイルのディレクトリを指定します。 * 注： * 制御ファイルが複数のディレクトリにある場合、これらのディレクトリの名前はカンマで区切ります。
 a| 
文字列の配列



 a| 
sm_created ファイルディレクトリ
 a| 
データファイルディレクトリを指定します。 * 注： * データファイルが複数のディレクトリにある場合、これらのディレクトリの名前はカンマで区切ります。
 a| 
文字列の配列



 a| 
ユーザー定義（ user_defined ）
 a| 
ユーザが定義する追加のパラメータを指定します。ポリシーとして使用されるプラグインでは、ユーザ定義のパラメータは使用できません。
 a| 
ユーザ定義

|===