---
permalink: windows/reference_the_smosmsapbackup_unmount_command.html 
sidebar: sidebar 
keywords: run, backup, unmount, command, smo 
summary: backup unmount コマンドを実行して、バックアップをアンマウントできます。 
---
= smo backup unmount コマンドを使用します
:icons: font
:imagesdir: ../media/


[role="lead"]
backup unmount コマンドを実行して、バックアップをアンマウントできます。



== 構文

[listing]
----

        smo backup unmount
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id id\]
\[-force\]
\[-dump\]
\[-quiet \| -verbose\]
----


== パラメータ

* * -profile profile_name *
+
バックアップをアンマウントするプロファイルを指定します。プロファイルには、データベースの識別子およびその他のデータベース情報が含まれています。

* * -id id *
+
指定した GUID を持つバックアップをアンマウントします。GUID はバックアップを作成するときに SnapManager によって生成されます。各バックアップの GUID を表示する場合は、 smo backup list コマンドを使用します。

* * - ラベルラベル *
+
指定したラベルを持つバックアップをアンマウントします。

* *-data*
+
データファイルを指定します。

* *-archivelogs*
+
アーカイブログファイルを指定します。

* * -dump*
+
アンマウント処理が成功または失敗したあとにダンプファイルを収集します。

* * -force *
+
バックアップに関連付けられたリソースを解放する際に問題が発生した場合も、バックアップをアンマウントします。SnapManager がバックアップをアンマウントし、関連付けられているすべてのリソースをクリーンアップします。ログにアンマウント処理が正常に完了したことが記録されていますが、ログにエラーがある場合は、リソースを手動でクリーンアップしなければならないことがあります。

* * - Quiet *
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* * -verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。





== 例

次に、アンマウント処理の例を示します。

[listing]
----
# smo backup unmount -label test -profile SALES1 -verbose
----
[listing]
----
[INFO ]: SMO-13051: Process PID=9788
[INFO ]: SMO-13036: Starting operation Backup Unmount on host hadley.domain.private
[INFO ]: SMO-13036: Starting operation Backup Unmount on host hadley.domain.private
[INFO ]: SMO-13046: Operation GUID 8abc015738849a3d0138849a43900001 starting on Profile FAS_P1
[INFO ]: SD-00031: Beginning to disconnect filesystem(s) [C:\SnapManager_auto_mounts\H-2012071400592312_0, C:\SnapManager_auto_mounts\I-2012071400592328_0].
[INFO ]: SD-00032: Finished disconnecting filesystem(s) [C:\SnapManager_auto_mounts\H-2012071400592312_0, C:\SnapManager_auto_mounts\I-2012071400592328_0].
[INFO ]: SMO-13048: Backup Unmount Operation Status: SUCCESS
[INFO ]: SMO-13049: Elapsed Time: 0:07:26.754
----
* 関連情報 *

xref:task_unmounting_backups.adoc[バックアップのアンマウント]
