---
permalink: windows/reference_the_smosmsapcredential_set_command.html 
sidebar: sidebar 
keywords: command, credential, user, access, secure, resource, host, repositories, repository, smo, password 
summary: このコマンドを使用すると、ホスト、リポジトリ、データベースプロファイルなどのセキュアなリソースにアクセスするためのクレデンシャルをユーザに設定できます。ホストパスワードは、 SnapManager が実行されているホスト上のユーザのパスワードです。リポジトリのパスワードは、 SnapManager リポジトリスキーマが格納されている Oracle ユーザのパスワードです。プロファイルパスワードは、プロファイルを作成するユーザーが構成するパスワードです。ホストとリポジトリのオプションを指定して、オプションの -password オプションを指定した場合は、コマンド引数で指定したタイプのパスワードを入力するように求められます。 
---
= smo credential set コマンドです
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このコマンドを使用すると、ホスト、リポジトリ、データベースプロファイルなどのセキュアなリソースにアクセスするためのクレデンシャルをユーザに設定できます。ホストのパスワードは、 SnapManager が実行されているホストでのユーザのパスワードです。リポジトリのパスワードは、 SnapManager リポジトリスキーマが格納されている Oracle ユーザのパスワードです。プロファイルパスワードは、プロファイルを作成するユーザーが構成するパスワードです。ホストとリポジトリのオプションを指定して、オプションの -password オプションを指定した場合は、コマンド引数で指定したタイプのパスワードを入力するように求められます。



== 構文

[listing]
----

        smo credential set
\[-host
-name host_name
-username username\]
\[-password password\] \] \|
\[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username\] \[-password repo_password\] \]
-port repo_port \|
\[-profile
-name profile_name\]
\[-password password\] \]
\[-quiet \| -verbose\]
----


== パラメータ

* * - ホスト名 *
+
SnapManager を実行しているホストサーバの名前または IP アドレスを指定します。

+
host パラメータには、次のオプションがあります。

+
** -name host_name ：パスワードを設定するホストの名前を指定します。
** -username user_name ：ホスト上のユーザ名を指定します。
** -password password ：ホスト上のユーザのパスワードを指定します。


* * -repository -dbname *
+
プロファイルが格納されたデータベースの名前を指定します。グローバル名または SID を使用します。

+
repository パラメータには、次のオプションが含まれます。

+
** -dbnamerepo_service_name ：プロファイルを格納するデータベースの名前を指定します。グローバル名または SID を使用します。
** -host repo_host ：リポジトリ・データベースが稼働しているホスト・サーバの名前または IP アドレスを指定します。
** -login-username repo_username ：リポジトリが格納されたデータベースにアクセスするために必要なユーザ名を指定します。
** -password password ：リポジトリが格納されたデータベースにアクセスするために必要なパスワードを指定します。
** -port repo_port ：リポジトリが格納されているデータベースへのアクセスに使用する TCP ポート番号を指定します。


* * -profile-name profile_name *
+
データベースに関連付けられたプロファイルを指定します。

+
profile パラメータには、次のオプションが含まれています。

+
** -name profilename ：パスワードを設定するプロファイルの名前を指定します。
** -password password ：プロファイルへのアクセスに必要なパスワードを指定します。


* * - Quiet *
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* * -verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。





== リポジトリクレデンシャルを設定するコマンドの例

次に、リポジトリのクレデンシャルを設定する例を示します。

[listing]
----

smo credential set -repository -dbname SMOREPO -host hotspur -port 1521 -login -username chris
Password for chris@hotspur:1521/SMOREPO : ********
Confirm password for chris@hotspur:1521/SMOREPO : ********
----
[listing]
----
SMO-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMO-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----


== ホストクレデンシャルを設定するためのコマンドの例

ホストクレデンシャルは実際のオペレーティングシステムクレデンシャルを表すため、パスワードのほかにユーザ名も含める必要があります。

[listing]
----
smo credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----
* 関連情報 *

xref:concept_snapmanager_security.adoc[SnapManager によるセキュリティの維持方法]
