---
permalink: windows/reference_the_smosmsap_schedule_update_command.html 
sidebar: sidebar 
keywords: command, update, schedule, backup, smo 
summary: このコマンドは、バックアップのスケジュールを更新します。 
---
= smo schedule update コマンド
:icons: font
:imagesdir: ../media/


[role="lead"]
このコマンドは、バックアップのスケジュールを更新します。



== 構文

[listing]
----

        smo schedule update
-profile profile_name
-schedule-name schedule_name
\[-schedule-comment schedule_comment\]
-interval \{-hourly \| -daily \| -weekly \| -monthly \| -onetimeonly\}
-cronstring cron_string
-start-time \{start_time <yyyy-MM-dd HH:mm\>\}
-runasuser runasuser
\[-taskspec taskspec\]
-force
\[-quiet \| -verbose\]
----


== パラメータ

* * -profile profile_name *
+
バックアップをスケジュールするデータベースに関連するプロファイルの名前を指定します。プロファイルには、データベースの識別子およびその他のデータベース情報が含まれています。

* * -schedule - name schedule_name * と入力します
+
スケジュールに指定する名前を指定します。

* * -schedule - comment schedule_comment *
+
バックアップのスケジュール設定に関するコメントを指定します。

* * -interval ｛ -hourly | -daily | -weekly | -monthly | -onetimeonly ｝ * を使用できます
+
バックアップを作成する間隔を示します。バックアップのスケジュールは、毎時、毎日、毎週、毎月、または 1 回だけ設定できます。

* *cronstring cron_string*
+
cronstring を使用してバックアップをスケジュールするように指定します。CronTrigger のインスタンスの構成には cron 式が使用されます。cron 式は、実際には 7 つのサブ式で構成される文字列です。

+
** 1 は秒を表します
** 2 は分を表します
** 3 は時間を表します
** 4 は 1 か月の 1 日を表します
** 5 は月を表します
** 6 は 1 週間のうちの 1 日を表します
** 7 は年を表します（オプション）。


* * -start-time yyyy-mm-dd HH ： MM *
+
スケジュール処理の開始時刻を指定します。スケジュールの開始時刻は、 yyyy-mm-dd HH ： MM の形式で指定します。

* *-runAsUser runAsUser*
+
バックアップのスケジュール設定時にスケジュールされたバックアップ処理のユーザを変更するように指定します。

* *-taskspec taskspec *
+
バックアップ処理の前処理または後処理に使用できるタスク仕様 XML ファイルを指定します。XML ファイルの完全なパスを指定する必要があります。このパスには -taskspec オプションがあります。


