---
permalink: windows/reference_error_messages.html 
sidebar: sidebar 
keywords: error, message, information, operation 
summary: ここでは、さまざまな SnapManager 処理に関連するエラーメッセージについて説明します。 
---
= エラーメッセージ
:icons: font
:imagesdir: ../media/


[role="lead"]
ここでは、さまざまな SnapManager 処理に関連するエラーメッセージについて説明します。



== 最も一般的なエラーメッセージです

次の表に、 SnapManager for Oracle に関連する最も一般的なエラーと重要なエラーを示します。

|===


| エラーメッセージです | 説明 | 解決策： 


 a| 
SD-10038 ：ファイルシステムに書き込みができません。
 a| 
SnapManager プロセスには、ファイルシステムへの書き込みアクセス権がありません。
 a| 
SnapManager プロセスがファイルシステムに書き込みアクセスできることを確認する必要があります。これを修正した後、別のスナップショットを作成する必要がある場合があります。



 a| 
SMO -05075: プロファイルを作成できません。DP / XDP 関係を適切に設定するか、基盤となる関係ごとに正しい保護ポリシーを選択する必要があります。
 a| 
基盤となるボリュームが SnapVault 関係または SnapMirror 関係にない。
 a| 
ソースボリュームとデスティネーションボリュームの間にデータ保護関係を設定し、その関係を初期化する必要があります。



 a| 
smo -05503 ：プロファイルに同じ名前を指定している。プロファイル名を変更するには、別の名前を指定してください。
 a| 
同じ名前のプロファイルはリポジトリに存在できません
 a| 
使用されていないプロファイル名を指定してください。



 a| 
SMO -0505: データセットメタデータを更新できません。
 a| 
データセットが削除されているか、存在しません。
 a| 
データセットのメタデータを更新する前に、 NetApp Management Console を使用してデータセットが存在することを確認します。



 a| 
SMO -0506 ：プロファイル上で実行中の処理があるため、プロファイルを更新できません。処理が完了してからプロファイルを更新する必要があります。
 a| 
バックアップ、リストア、クローニングの各処理が実行中の場合、プロファイルを更新できません。
 a| 
現在の処理が完了したら、プロファイルを更新してください。



 a| 
SMO -05509 ：無効なアーカイブログのプライマリ保持期間 - 正の整数値を指定します。
 a| 
アーカイブログバックアップの保持期間を負の値にすることはできません。
 a| 
アーカイブログバックアップの保持期間には正の値を指定します。



 a| 
SMO -07463 ：このバックアップリストアでは、データベースが必要な状態にある必要があります。データベースを必要な状態にできませんでした。
 a| 
データベースがバックアップ処理に必要な状態ではありません。
 a| 
バックアップコピーを作成する前に、データベースが関連する状態であることを確認します。リストアされるデータベースの状態は、実行するリストアプロセスのタイプ、およびリストアに含めるファイルのタイプによって異なります。



 a| 
SMO -09315 ：リポジトリのアップグレードまたは更新処理の実行後、通知ホストの詳細で概要通知を更新しないかぎり、以前のバージョンで設定された通知に関する概要通知を受信できない場合があります。
 a| 
ローリングアップグレードの実行後は、リポジトリの通知設定は行われません。
 a| 
ローリングアップグレードの実行後、通知を受信するように通知の概要設定を更新します。



 a| 
SM0-02076 ：ラベル名にアンダースコア以外の特殊文字を使用することはできません。
 a| 
ラベル名には、アンダースコア以外の特殊文字が含まれています。
 a| 
ラベル名は、プロファイル内で一意である必要があります。名前には、アルファベット、数字、アンダースコア（ _ ）、およびハイフン（ - ）を使用できます（ 1 文字目をハイフンにすることはできません）。ラベルにアンダースコア以外の特殊文字が含まれていないことを確認してください。



 a| 
SMO -0308 ：スケジュール開始時に例外が発生しました： java.lang.NullPointerException
 a| 
プロファイルホストの完全修飾ドメイン名（ FQDN ）がシステムのホスト名ではなく設定されており、プロファイルホストの FQDN を解決できません。
 a| 
FQDN ではなく、システムのホスト名を使用してください。



 a| 
ExecuteRestoreSteps のエラー： oracle-10003 ： SQL 「 DROP DISKGROU; コントロールディスクグループ名。 Oracle データベース +ASM1 に対する内容を含む。 ORA-15039 ：ディスクグループが削除されない ORA-15027 ：ディスクグループがアクティブに使用される、「コントロールディスクグループ名」はディスマウントされない
 a| 
制御ファイルを含むバックアップをリストアする処理で、制御ディスクグループが削除されません。この問題は、制御ディスクグループに古いバックアップ制御ファイルがある場合に発生します。
 a| 
古いバックアップされた制御ファイルを特定し、手動で削除します。



 a| 
rman-06004: リカバリカタログデータベースからの Oracle エラー : ORA-01424: エスケープ文字の後に文字がないか、不正です
 a| 
SnapManager が RMAN に統合されている場合、バックアップ作成処理でカタログからバックアップコピーを削除できませんでした。
 a| 
RMAN からバックアップを削除するために使用する外部スクリプトがあるかどうかを確認します。RMAN で CROSCHECK バックアップコマンドを実行して RMAN リポジトリを更新し、 resync catalog コマンドを使用して、ターゲットデータベースの制御ファイルをリカバリカタログと同期させます。



 a| 
[debug] ：バックアップの削除中に例外が発生しました。java.lang.IllegalStateException ： [Assertion failed] - この状態不変は true である必要があります
 a| 
1 つの処理 ID に対して複数の Snapshot コピーが作成される。
 a| 
Snapshot コピーを手動で削除し、スクリプトを使用してリポジトリからエントリを削除します。



 a| 
システム時間と SnapManager によってログファイルに表示される時間が一致しないか、同期されていません。
 a| 
タイムゾーンの変更は、 Java 7 ではまだサポートされていません。
 a| 
Oracle が提供する tzupdater パッチを適用します。



 a| 
DiSC -00001 ：ストレージを検出できません。次の ID が存在しないか、必要なタイプの ASM ファイルではありません
 a| 
データファイル、制御ファイル、または REDO ログは、 ASM データベースで多重化されます。
 a| 
Oracle 多重化を削除します。



 a| 
ORA-01031 ：権限がありません。適切な権限を持つユーザとして実行するように SnapManager Windows サービスが設定されていること、および ORA_DBA グループにユーザが含まれていることを確認します。
 a| 
SnapManager に十分な権限がありません。SnapManager サービスアカウントは ORA_DBA グループに属していません。
 a| 
デスクトップ上の * Computer * アイコンを右クリックし、 * Manage * を選択して、 SnapManager サービスのユーザー・アカウントが ORA_DBA グループの一部であることを確認します。ローカルユーザとローカルグループをチェックし、 ORA_DBA グループにアカウントが含まれていることを確認してください。ユーザがローカル管理者の場合は、そのユーザがドメイン管理者ではなくグループに属していることを確認します。



 a| 
0001-SMO-02016 ：このバックアップ処理でバックアップされない外部テーブルがデータベースにある可能性があります（このバックアップではデータベースが開かれていなかったため、 All_external_locations は外部テーブルが存在するかどうかを判別できませんでした）。
 a| 
SnapManager では、外部テーブル（たとえば、 .dbf ファイルに格納されていないテーブル）はバックアップされません。この問題は、バックアップ中にデータベースが開かれておらず、 SnapManager が外部テーブルが使用されているかどうかを判断できないために発生します。
 a| 
バックアップ中にデータベースが開かれなかったために、この処理でバックアップされない外部テーブルがデータベースに存在する場合があります。



 a| 
0002-332 管理エラー： Operations Manager サーバ「 dfm_server 」のユーザ名に対する sd.snapshot.Clone アクセスを確認できませんでした。理由：無効なリソースが指定されました。Operations Manager サーバ「 dfm_server 」に ID が見つかりません。
 a| 
適切なアクセス権限とロールが設定されていません。
 a| 
コマンドを実行するユーザのアクセス権限またはロールを設定します。



 a| 
[WARN] FLOW-11011 ：操作は中断されました [error] FLOW11008 ：操作が失敗しました： Java ヒープスペース。
 a| 
データベース内のアーカイブログファイルの数が、許容される最大数を超えています。
 a| 
. SnapManager のインストールディレクトリに移動します。
. launch-java ファイルを開きます。
. Java ヒープ領域パラメータ java -Xmx160m`Java heap space パラメータの値を大きくしますたとえば 'javA-Xmx200m というデフォルト値の 160m から 200 m に変更できます




 a| 
smo -21019 ：デスティネーションのアーカイブ・ログ削除が、「 E ： \dest 」、理由：「 Oracle-00101 ： Error executing RMAN command ： [delete noprompt ARCHIVE'E ： \dest'] 」で失敗しました。
 a| 
アーカイブ・ログの削除は、いずれかのデスティネーションで失敗します。このようなシナリオでは、 SnapManager は、アーカイブログファイルを他のデスティネーションから削除し続けます。アクティブ・ファイルシステムからファイルを手動で削除した場合、 RMAN はアーカイブ・ログ・ファイルをそのデスティネーションから削除しません。
 a| 
SnapManager ホストから RMAN に接続します。RMAN CROSCHECK ARCHIVELOG ALL コマンドを実行して、アーカイブログファイルの削除処理を再度実行します。



 a| 
SMO -13032 ：処理を実行できません：アーカイブログのプルーニング。Root 原因： RMAN Exception ： oracle-00101 ： RMAN コマンドの実行中にエラーが発生しました。
 a| 
アーカイブログの保存先からアーカイブログファイルが手動で削除されます。
 a| 
SnapManager ホストから RMAN に接続します。RMAN CROSCHECK ARCHIVELOG ALL コマンドを実行して、アーカイブログファイルの削除処理を再度実行します。



 a| 
シェル出力を解析できません：（ java.util.regex.Matcher[pattern = command complete] ）region=0,18 lastmatch=) が一致しません ( 名前 :backup_script) シェル出力を解析できません : (java.util.regex.Matcher[pattern=command complete)Region = 0.25 lastmatch= ] ）が一致しません（説明：バックアップスクリプト）。

シェル出力を解析できません：（ java.util.regex.Matcher[pattern = command complete] ）region = 0 、 9 lastmatch=] ）が一致しません（ timeout ： 0 ）。
 a| 
プリタスクスクリプトまたはポストタスクスクリプトで環境変数が正しく設定されていません。
 a| 
プリタスクスクリプトまたはポストタスクスクリプトが標準の SnapManager プラグイン構造に準拠しているかどうかを確認します。スクリプトでの環境変数の使用については、を参照してください追加情報 xref:concept_operations_in_task_scripts.adoc[タスクスクリプト内の操作]。



 a| 
ORA-01450 ：キーの最大長（ 6398 ）を超えました。
 a| 
SnapManager 3.2 for Oracle から SnapManager 3.3 for Oracle へのアップグレードを実行すると、アップグレード処理が失敗し、次のエラーメッセージが表示されます。この問題は、次のいずれかの理由で発生する可能性があります。

* リポジトリが存在するテーブルスペースのブロックサイズが 8k 未満である。
* NLS_LENGTH_SEMANTICS パラメータは char に設定されます

 a| 
次のパラメータに値を割り当てる必要があります。

* block_size = 8192 です
* NLS_LENGTH= バイト


パラメータ値を変更したら、データベースを再起動する必要があります。

詳細については、記事 2017632 を参照してください。

|===


== データベース・バックアップ・プロセスに関連するエラー・メッセージ（ 2000 シリーズ）

次の表に、データベースバックアッププロセスに関連する一般的なエラーを示します。

|===


| エラーメッセージです | 説明 | 解決策： 


 a| 
smo -02066 ：バックアップはデータ・バックアップ「データ・ログ」に関連付けられているため、アーカイブ・ログ・バックアップ「データ・ログ」を削除したり、解放したりすることはできません。
 a| 
アーカイブログのバックアップがデータファイルのバックアップとともに作成され、アーカイブログのバックアップを削除しようとしました。
 a| 
force オプションを使用して、バックアップを削除または解放します。



 a| 
smo -02067 ：バックアップはデータ・バックアップ「データ・ログ」に関連付けられ、指定された保持期間内であるため、アーカイブ・ログ・バックアップ「データ・ログ」を削除したり解放したりすることはできません。
 a| 
アーカイブログバックアップはデータベースバックアップに関連付けられており、保持期間内にあるため、アーカイブログバックアップを削除しようとしました。
 a| 
force オプションを使用して、バックアップを削除または解放します。



 a| 
smo -07142 ：除外パターン <Exclusion] のために除外されたアーカイブ・ログ。
 a| 
プロファイルの作成またはバックアップの作成処理では、一部のアーカイブ・ログ・ファイルを除外します。
 a| 
対処は不要です。



 a| 
smo -07155 ： <count> archived log files do not exist in the active file system.これらのアーカイブログファイルはバックアップに含まれません。
 a| 
プロファイルの作成処理またはバックアップの作成処理中に、アクティブファイルシステムにアーカイブログファイルが存在しません。これらのアーカイブ・ログ・ファイルは、バックアップに含まれません。
 a| 
対処は不要です。



 a| 
smo -07148 ：アーカイブされたログ・ファイルは使用できません。
 a| 
プロファイルの作成処理またはバックアップの作成処理中に、現在のデータベースに対応したアーカイブログファイルは作成されません。
 a| 
対処は不要です。



 a| 
smo -07150 ：アーカイブされたログ・ファイルが見つかりません。
 a| 
ファイルシステムにアーカイブログファイルがないか、プロファイルの作成処理またはバックアップの作成処理で除外されています。
 a| 
対処は不要です。



 a| 
SMO -13032 ： Cannot perform operation ： Backup Create .Root 原因： oracle-20001 ：データベースインスタンス dfcln1 に対して状態をオープンに変更しようとしてエラーが発生しました。 Oracle-20004 ： RESETLOGS オプションを指定せずにデータベースを開くことを期待していますが、 RESETLOGS オプションを指定してデータベースを開く必要があると Oracle から報告されています。予期せずログをリセットしないようにするため、プロセスは続行されません。RESETLOGS オプションを指定せずにデータベースを開くことができることを確認してから、もう一度実行してください。
 a| 
no-resetlogs オプションで作成されたクローンデータベースをバックアップしようとします。クローンデータベースは完全なデータベースではありません。ただし、クローンデータベースではプロファイルやバックアップの作成などの SnapManager 処理は実行できますが、クローンデータベースが完全なデータベースとして設定されていないため SnapManager 処理は失敗します。
 a| 
クローンデータベースをリカバリするか、データベースを Data Guard Standby データベースに変換します。

|===


== リストア・プロセスに関連するエラー・メッセージ（ 3000 シリーズ）

次の表に、リストアプロセスに関連する一般的なエラーを示します。

|===


| エラーメッセージです | 説明 | 解決策： 


 a| 
smo -03031 ：バックアップのストレージ・リソースがすでに解放されているため、 Backup <variable> のリストアでは、リストア仕様が必要です。
 a| 
ストレージ・リソースが解放されているバックアップを、リストア仕様を指定しないでリストアしようとしました。
 a| 
リストア仕様を指定します。



 a| 
smo -03032 ：リストア仕様では、バックアップ用のストレージ・リソースがすでに解放されているため、リストアするファイルのマッピングを指定する必要があります。マッピングが必要なファイルは次のとおりです。 <variable> from Snapshots:<variable>
 a| 
ストレージ・リソースが解放されているバックアップを、リストア対象の全ファイルのマッピングが定義されていないリストア仕様を指定してリストアしようとしました。
 a| 
リストア仕様ファイルを修正して、マッピングがリストア対象のファイルと一致するようにします。



 a| 
Oracle-30028: ログファイル <filename> をダンプできません。ファイルが見つからないか、アクセスできないか、破損している可能性があります。このログファイルはリカバリには使用されません。
 a| 
オンライン REDO ログファイルまたはアーカイブログファイルをリカバリに使用できません。このエラーは次の理由で発生します。

* エラーメッセージに記載されているオンラインの REDO ログファイルまたはアーカイブログファイルには、リカバリに適用する十分な変更番号がありません。これは、データベースがトランザクションなしでオンラインになっている場合に発生します。REDO ログまたはアーカイブログファイルには、リカバリに適用できる有効な変更番号はありません。
* エラーメッセージに記載されたオンライン REDO ログファイルまたはアーカイブログファイルには、 Oracle に対する十分なアクセス権限がありません。
* エラーメッセージに記載されたオンライン REDO ログファイルまたはアーカイブログファイルが破損しており、 Oracle で読み取ることができません。
* エラーメッセージに記載されているオンライン REDO ログファイルまたはアーカイブログファイルが、記載されたパスに見つかりません。

 a| 
エラーメッセージに記載されているファイルがアーカイブログファイルであり、リカバリのために手動で指定した場合は、そのファイルに Oracle に対するフルアクセス権限があることを確認します。ファイルにフルアクセス権限がある場合でも、 メッセージが続くと、アーカイブログファイルにリカバリに適用される変更番号がないため、このメッセージは無視してかまいません。

|===


== クローニングプロセスに関連するエラーメッセージ（ 4000 シリーズ）

次の表に、クローニングプロセスに関連する一般的なエラーを示します。

|===


| エラーメッセージです | 説明 | 解決策： 


 a| 
SMO -04133 ：ダンプの送信先が存在しないことを確認してください
 a| 
SnapManager を使用して新しいクローンを作成していますが、その新しいクローンで使用されるダンプデスティネーションはすでに存在します。ダンプの送信先が存在する場合、 SnapManager でクローンを作成することはできません。
 a| 
クローンを作成する前に、古いダンプデスティネーションを削除するか、名前を変更してください。



 a| 
SMO -13032 ：処理を実行できません：クローンの作成。Root 原因： Oracle-00001 ： SQL の実行中にエラーが発生しました： [ALTER DATABASE OPEN RESETLOGS;]返されたコマンドは次のとおりです。 ORA-3856 ： Cannot mark unnamed_instance_2 （ REDO スレッド 2 ） as enabled 。
 a| 
次のセットアップを実行してスタンバイデータベースからクローンを作成すると、クローンの作成に失敗します。

* スタンバイは、 RMAN を使用してデータファイルのバックアップを作成し、

 a| 
クローンを作成する前に、クローン仕様ファイルに _no-recovery_through _resetlogs=true パラメータを追加します。追加情報については、 Oracle のマニュアル（ ID 334899.1 ）を参照してください。Oracle MetaLink のユーザー名とパスワードがあることを確認します。



 a| 
 a| 
クローン仕様ファイルで、パラメータの値を指定していません。
 a| 
パラメータの値を指定するか、クローン仕様ファイルで不要な場合はそのパラメータを削除する必要があります。

|===


== プロファイル管理プロセスに関連するエラー・メッセージ（ 5000 シリーズ）

次の表に、クローニングプロセスに関連する一般的なエラーを示します。

|===


| エラーメッセージです | 説明 | 解決策： 


 a| 
smo -20600 ：プロファイル「 profile1 」がリポジトリ「 repo_name 」に見つかりません。「 profile sync 」を実行して、プロファイル / リポジトリのマッピングを更新してください。
 a| 
プロファイルの作成に失敗した場合は、ダンプ処理を実行できません。
 a| 
スモシステムダンプを使用します。

|===


== バックアップ・リソースの解放に関するエラー・メッセージ（ Backup 6000 シリーズ）

次の表に、バックアップタスクに関する一般的なエラーを示します。

|===


| エラーメッセージです | 説明 | 解決策： 


 a| 
SMO -06030 ：使用中のためバックアップを削除できません： < 変数 >
 a| 
バックアップがマウントされている場合、クローンがある場合、または保持期間が無制限とマークされている場合に、コマンドを使用してフリーバックアップ処理を実行しようとしました。
 a| 
バックアップをアンマウントするか、保持ポリシーを無制限に変更します。クローンが存在する場合は削除します。



 a| 
smo -06045 ： Cannot free backup <variable> because the storage resources for the backup already been freed
 a| 
バックアップがすでに解放されている場合、コマンドを使用してバックアップの解放処理を実行しようとしました。
 a| 
すでに解放されているバックアップは解放できません。



 a| 
SMO -06047 ：解放できるのは成功したバックアップのみです。バックアップ <ID> のステータスは <status> です。
 a| 
バックアップのステータスが失敗したときに、コマンドを使用してバックアップの解放処理を実行しようとしました。
 a| 
バックアップが正常に完了してから再試行してください。



 a| 
smo -13082 ： Cannot perform operation <variable> on backup <ID> because the storage resources have been freed 」
 a| 
コマンドを使用して、ストレージ・リソースが解放されているバックアップをマウントしようとしました。
 a| 
ストレージ・リソースが解放されているバックアップは、マウント、クローニング、または検証できません。

|===


== ローリングアップグレードプロセスに関連するエラーメッセージ（ 9000 シリーズ）

次の表に、ローリングアップグレードプロセスに関連する一般的なエラーを示します。

|===


| エラーメッセージです | 説明 | 解決策： 


 a| 
SMO -09234 ：古いリポジトリに次のホストが存在しません。< ホスト名 > 。
 a| 
以前のリポジトリバージョンに存在しないホストのローリングアップグレードを実行しようとしました。
 a| 
以前のバージョンの SnapManager CLI から repository show -repository コマンドを使用して、ホストが以前のリポジトリに存在するかどうかを確認します。



 a| 
SMO -0955: 新しいリポジトリに次のホストが存在しません。< ホスト名 > 。
 a| 
新しいリポジトリバージョンに存在しないホストのロールバックを実行しようとしました。
 a| 
新しいリポジトリにホストが存在するかどうかを確認するには、新しいバージョンの SnapManager CLI で repository show -repository コマンドを使用します。



 a| 
smo -09256 ：指定されたホスト <hostname> に新しいプロファイル <profilename> が存在するため、ロールバックはサポートされていません。
 a| 
リポジトリに存在する新しいプロファイルを含むホストをロールバックしようとしました。ただし、これらのプロファイルは、以前のバージョンの SnapManager のホストには存在しませんでした。
 a| 
ロールバックの前に、 SnapManager の以降のバージョンまたはアップグレードされたバージョンの新しいプロファイルを削除します。



 a| 
smo -09257 ：バックアップ <backupid> が新しいホストにマウントされているため、ロールバックはサポートされていません。
 a| 
バックアップをマウントしている SnapManager ホストの新しいバージョンをロールバックしようとしました。これらのバックアップは、以前のバージョンの SnapManager ホストにはマウントされていません。
 a| 
新しいバージョンの SnapManager ホストでバックアップをアンマウントし、ロールバックを実行します。



 a| 
SMO -09258 ：バックアップ <backupid> が新しいホストでアンマウントされているため、ロールバックはサポートされていません。
 a| 
アンマウントされているバックアップがある新しいバージョンの SnapManager ホストをロールバックしようとしました。
 a| 
新しいバージョンの SnapManager ホストにバックアップをマウントし、ロールバックを実行する。



 a| 
smo -09298 ：上位バージョンのホストがすでに存在するため、このリポジトリを更新できません。代わりに、すべてのホストのロールアップグレードを実行してください。
 a| 
単一のホストでローリングアップグレードを実行し、そのホストのリポジトリを更新した。
 a| 
すべてのホストでローリングアップグレードを実行します。



 a| 
SMO -09297 ：制約の有効化中にエラーが発生しました。リポジトリの状態が不整合である可能性があります。現在の処理の前に作成したリポジトリのバックアップをリストアすることを推奨します。
 a| 
リポジトリデータベースが不整合な状態のままになっている場合は、ローリングアップグレードまたはロールバック操作を実行しようとしました。
 a| 
以前にバックアップしたリポジトリをリストアします。

|===


== 作業の実施 (12,000 シリーズ )

次の表に、操作に関連する一般的なエラーを示します。

|===


| エラーメッセージです | 説明 | 解決策： 


 a| 
smo -12347 [ エラー ] ： SnapManager サーバがホスト <host> およびポート <port> で実行されていません。このコマンドは、 SnapManager サーバを実行しているホストで実行してください。
 a| 
プロファイルの設定中に、ホストおよびポートに関する情報を入力しました。ただし SnapManager 、 SnapManager サーバは指定したホストおよびポートで実行されていないため、これらの処理を実行できません。
 a| 
SnapManager サーバを実行しているホストでコマンドを入力します。lsnrctl status コマンドを使用してポートをチェックし、データベースが実行されているポートを確認できます。必要に応じて、バックアップコマンドでポートを変更します。

|===


== プロセスコンポーネントの実行（ 13,000 シリーズ）

次の表に、 SnapManager のプロセスコンポーネントに関連する一般的なエラーを示します。

|===


| エラーメッセージです | 説明 | 解決策： 


 a| 
smo -13083 ： snapname パターンの値が「 x 」の場合は、アルファベット、数字、アンダースコア、ダッシュ、波かっこ以外の文字が含まれます。
 a| 
プロファイルを作成するときは、 snapname パターンをカスタマイズしますが、使用できない特殊文字が含まれています。
 a| 
アルファベット、数字、アンダースコア、ダッシュ、および波かっこ以外の特殊文字を削除します。



 a| 
smo -13084 ： snapname pattern with value "x" does not contain the same number of left and right ブレース .
 a| 
プロファイルを作成しているときに、 snapname パターンをカスタマイズしていますが、左波カッコと右波カッコは一致しません。
 a| 
snapname パターンに、対応する開閉用ブラケットを入力します。



 a| 
smo -13085 ：値が「 x 」の snapname パターンには無効な変数名「 y 」が含まれています。
 a| 
プロファイルを作成しているときは、 snapname パターンをカスタマイズしていますが、変数は使用できません。
 a| 
問題のある変数を削除します。使用できる変数のリストについては、を参照してください xref:concept_snapshot_copy_naming.adoc[Snapshot コピーの命名規則]。



 a| 
smo -13086 ：値が「 x 」の snapname パターンには変数「 smid 」を含める必要があります。
 a| 
プロファイルを作成する際には、 snapname パターンをカスタマイズしますが、必須の smid 変数は省略しています。
 a| 
必要な smid 変数を挿入します。

|===


== SnapManager ユーティリティに関連するエラーメッセージ（ 14,000 シリーズ）

次の表に、 SnapManager ユーティリティに関連する一般的なエラーを示します。

|===


| エラーメッセージです | 説明 | 解決策： 


 a| 
smo -14501 ：メール ID を空にすることはできません。
 a| 
E メールアドレスが入力されていません。
 a| 
有効な E メールアドレスを入力してください。



 a| 
SMO -14502 ：メールの件名を空白にすることはできません。
 a| 
E メールの件名が入力されていません。
 a| 
適切な E メールの件名を入力します。



 a| 
smo -14506 ：メール・サーバのフィールドを空白にすることはできません。
 a| 
E メールサーバのホスト名または IP アドレスを入力していません。
 a| 
有効なメールサーバのホスト名または IP アドレスを入力してください。



 a| 
SMO -14507 ： Mail Port フィールドを空白にすることはできません。
 a| 
E メールポート番号が入力されていません。
 a| 
E メールサーバのポート番号を入力します。



 a| 
SMO -14508 ：メール ID を空白にすることはできません。
 a| 
送信者の E メールアドレスが入力されていません。
 a| 
有効な送信者の E メールアドレスを入力してください。



 a| 
SMO -14509 ：ユーザ名を空白にすることはできません。
 a| 
認証を有効にしましたが、ユーザ名が指定されていません。
 a| 
E メール認証のユーザ名を入力します。



 a| 
smo -14510 ：パスワードを空にすることはできません。パスワードを入力してください。
 a| 
認証を有効にしましたが、パスワードが指定されていません。
 a| 
E メール認証パスワードを入力します。



 a| 
smo -14550 ： E メールのステータスが <success / failure> です。
 a| 
ポート番号、メールサーバ、または受信者の E メールアドレスが無効です。
 a| 
E メールの設定時に適切な値を指定します。



 a| 
SMO -14559 ： E メール通知の送信に失敗しました： <error> 。
 a| 
ポート番号が無効であるか、メールサーバが無効であるか、受信者のメールアドレスが無効である可能性があります。
 a| 
E メールの設定時に適切な値を指定します。



 a| 
SMO -14560 ：通知に失敗しました：通知設定を使用できません。
 a| 
通知設定を使用できないため、通知の送信に失敗しました。
 a| 
通知設定を追加



 a| 
SMO -14565 ：無効な時間形式です。時刻の形式は HH ： MM で入力してください。
 a| 
時刻の形式が正しくありません。
 a| 
時刻を hh:mm の形式で入力します。



 a| 
SMO -14566 ：無効な日付値です。有効な日付範囲は 1~31 です。
 a| 
設定された日付が正しくありません。
 a| 
日付は 1~31 の範囲で指定します。



 a| 
SMO -14567 ：無効な日付値です。有効な日付範囲は 1 ～ 7 です。
 a| 
設定された日付が正しくありません。
 a| 
1 ～ 7 の範囲で日を入力します。



 a| 
SMO -14569 ：サーバで概要通知スケジュールを開始できませんでした。
 a| 
原因不明のエラーにより SnapManager サーバがシャットダウンしました。
 a| 
SnapManager サーバを起動します。



 a| 
SMO -14570 ：概要通知がありません。
 a| 
概要通知が設定されていません。
 a| 
サマリー通知を設定します。



 a| 
smo -14571 ：プロファイル通知と概要通知の両方を有効にすることはできません。
 a| 
プロファイル通知とサマリー通知の両方のオプションを選択しました。
 a| 
プロファイル通知またはサマリー通知のいずれかをイネーブルにします。



 a| 
SMO -14572 ：通知の成功または失敗オプションを指定します。
 a| 
成功オプションまたは失敗オプションが有効になっていません。
 a| 
success または failure オプションか、あるいはその両方を選択する必要があります。

|===
* 関連情報 *

xref:concept_snapshot_copy_naming.adoc[Snapshot コピーの命名規則]
