---
permalink: windows/reference_the_smosmsap_history_set_command.html 
sidebar: sidebar 
keywords: history, run, set, command, configure, operation, history, smo 
summary: history set コマンドを実行すると、履歴を表示する操作を設定できます。 
---
= smo history set コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
history set コマンドを実行すると、履歴を表示する操作を設定できます。



== 構文

[listing]
----

        smo history set
-profile \{-name profile_name \[profile_name1, profile_name2\] \| -all
-repository
-login \[password repo_password\]
-username repo_username
-host repo_host
-dbname repo_dbname
-port repo_port}
-operation \{-operations operation_name \[operation_name1, operation_name2\] \| -all\}
-retain
{-count retain_count \| -daily daily_count \| -monthly monthly_count \| -weekly weekly_count}
[-quiet | -verbose]
----


== パラメータ

* * -profile profile *
+
プロファイルの名前を指定します。名前は 30 文字以内で指定し、ホスト内で一意である必要があります。

* * - リポジトリ *
+
プロファイルが格納されるデータベースの詳細を指定します。

* * -dbname repo_dbname *
+
プロファイルが格納されたデータベースの名前を指定します。グローバル名またはシステム ID を使用できます。

* * -host repo_host *
+
リポジトリ・データベースが置かれているホストの名前または IP アドレスを指定します。

* * - ログイン *
+
リポジトリ・ログインの詳細を指定します。

* * -username repo_username *
+
リポジトリ・データベースへのアクセスに必要なユーザ名を指定します。

* * -port repo_port *
+
リポジトリデータベースへのアクセスに使用する TCP （ Transmission Control Protocol ）ポート番号を指定します。

* * -operation ｛ operationsoperation_name [operation_name1 、 operation_name2 ]|-all *
+
履歴を設定する SnapManager 操作を指定します。

* * -retain ｛ -tretretains_count | -dailydaily_count | -monthly -monthly_schedule_count| -weeklyweeklyweeklyweekly_count ｝ *
+
バックアップの作成、バックアップの検証、リストアとリカバリ、およびクローン作成の各処理の保持クラスを指定します。保持クラスは、処理数、日数、週数、または月に基づいて設定されます。

* * - Quiet *
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* * -verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。





== コマンドの例

次の例は、バックアップ処理に関する情報を表示します。

[listing]
----
smo history set -profile -name PROFILE1 -operation -operations backup -retain -daily 6
 -verbose
----