---
permalink: windows/task_clearing_user_credentials_for_all_hosts_repositories_and_profiles.html 
sidebar: sidebar 
keywords: clear, cache, credentials, resource, host, resource, profile, delete 
summary: リソース（ホスト、リポジトリ、およびプロファイル）のクレデンシャルのキャッシュをクリアできます。これにより、コマンドを実行しているユーザのリソースクレデンシャルがすべて削除されます。キャッシュをクリアしたら、クレデンシャルを再度認証して、これらのセキュアなリソースにアクセスできるようにする必要があります。 
---
= すべてのホスト、リポジトリ、およびプロファイルのユーザ・クレデンシャルの消去
:icons: font
:imagesdir: ../media/


[role="lead"]
リソース（ホスト、リポジトリ、およびプロファイル）のクレデンシャルのキャッシュをクリアできます。これにより、コマンドを実行しているユーザのリソースクレデンシャルがすべて削除されます。キャッシュをクリアしたら、クレデンシャルを再度認証して、これらのセキュアなリソースにアクセスできるようにする必要があります。

. クレデンシャルを消去するには、 SnapManager CLI で smo credential clear コマンドを入力するか、 SnapManager GUI から * Admin * > * Credentials * > * Clear Cache * を選択します。
. SnapManager GUI を終了します。
+
注

+
** SnapManager GUI からクレデンシャルキャッシュをクリアした場合は、 SnapManager GUI を終了する必要はありません。
** SnapManager CLI からクレデンシャルキャッシュをクリアした場合は、 SnapManager GUI を再起動する必要があります。
** 暗号化されたクレデンシャルファイルを手動で削除した場合は、 SnapManager GUI を再起動する必要があります。


. クレデンシャルを再度設定するには、同じプロセスを繰り返して、リポジトリ、プロファイルホスト、およびプロファイルのクレデンシャルを設定します。ユーザクレデンシャルを再度設定する追加情報の場合は、「クレデンシャルキャッシュをクリアしたあとのクレデンシャルの設定」を参照してください。


* 関連情報 *

xref:reference_the_smosmsapcredential_clear_command.adoc[smo credential clear コマンド]
