---
permalink: windows/task_installing_snapmanager_for_oracle.html 
sidebar: sidebar 
keywords: install, snapmanager, host, database, manage, install 
summary: 管理対象のデータベースが 1 つ以上あるホストに SnapManager をインストールできます。インストールできる SnapManager インスタンスは、ホストごとに 1 つだけです。 
---
= SnapManager for Oracle をインストールしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理対象のデータベースが 1 つ以上あるホストに SnapManager をインストールできます。インストールできる SnapManager インスタンスは、ホストごとに 1 つだけです。

* インストール前に必要なタスクを完了しておく必要があります。
* 最新の SnapManager インストールパッケージをダウンロードする必要があります。
* すべてのターゲットホストに、適切なバージョンの SnapDrive for Windows をインストールし、設定する必要があります。
+
SnapDrive for Windows のインストールと設定については、 SnapDrive for Windows インストレーションアドミニストレーションガイドを参照してください。

+
.. SnapManager インストールファイルをダブルクリックします。
+
|===


| オペレーティングシステム | 使用する方法 


 a| 
Windows x86 の場合
 a| 
netapp.smo.windows-x86-version.exe



 a| 
Windows x64
 a| 
netapp.smo.windows-x64-version.exe

|===
+
次のメッセージが表示されます。パブリッシャを検証できませんでした。このソフトウェアを実行しますか？

.. [OK] をクリックします。
.. [ はじめに ] ウィンドウで、 [ * 次へ * ] をクリックします。
.. [Choose Install Folder] ( インストールフォルダの選択 ) ウィンドウで、 [*Next] ( 次へ ) をクリックしてデフォルトのインストール場所を受け入れるか、新しい場所を選択します。
+
デフォルトの場所は、 C ： \Program Files\NetApp\SnapManager for Oracle です。

.. [ メニューの可用性 ] ウィンドウで、 [ * 次へ * ] をクリックします。
.. Specify Service Properties （サービスプロパティの指定）ウィンドウで、 Windows サービスのアカウントおよびパスワード情報を入力します。
+
指定するアカウントは、次のグループのメンバーである必要があります。

+
*** ストレージ・システムのローカル・アドミニストレーション・グループ
*** ローカル管理者のグループ
*** ORA_DBA グループ：再起動後にサービスを自動的に開始するか ' 手動で開始するかを指定できます


.. [ インストール前の概要 ] ウィンドウで、 [*Install*] をクリックします。
.. Install Complete （インストールの完了）ウィンドウで、 * Next （次へ） * をクリックします。
.. [ 重要な情報 ] ウィンドウで、 [ 完了 ] をクリックしてインストーラを終了します。




インストールが完了したら、インストールが正常に完了したことを確認できます。

. SnapManager サーバを起動します。
+
.. Windows サービスウィンドウで、 *NetApp SnapManager version for Oracle* を選択します。
.. 左パネルで、 * スタート * をクリックします。


. SnapManager システムが正しく動作していることを確認します。
+
.. Start * > * Programs * > * NetApp * > * SnapManager for Oracle * > * Start SMO Command Line Interface （ CLI ；コマンドラインインターフェイス） * の順にクリックします。
.. コマンドラインインターフェイス（ CLI ）で、次のコマンドを入力します。 smo system verify the following message is displayed ： Operation ID number succeeded


+
number は、処理 ID 番号です。



* 関連情報 *

xref:concept_preparing_to_install_snapmanager_for_oracle.adoc[SnapManager for Oracle のインストールの準備をしています]

xref:concept_preinstallation_tasks.adoc[インストール前のタスク]

xref:task_downloading_snapmanager_for_oracle_installation_package.adoc[SnapManager for Oracle インストール・パッケージのダウンロード]

http://mysupport.netapp.com/["ネットアップサポートサイトのドキュメント： mysupport.netapp.com"]
