---
permalink: windows/task_configuring_e_mail_notification_for_a_new_profile.html 
sidebar: sidebar 
keywords: creating, new, profile, configure, email, notification, completion, database, operation, configuring 
summary: 新しいプロファイルを作成する場合、データベース処理が完了したときに E メール通知を受け取るようにを設定できます。 
---
= 新しいプロファイルの E メール通知を設定しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいプロファイルを作成する場合、データベース処理が完了したときに E メール通知を受け取るようにを設定できます。

* アラートの送信元 E メールアドレスを設定する必要があります。
* 複数の E メールアドレスを指定する場合は、カンマで区切って指定する必要があります。
+
カンマと次の E メールアドレスの間にスペースを入れないようにしてください。

+

NOTE: 一連の E メールアドレスは二重引用符で囲む必要があります。

+
.. 次のコマンドを入力します。 smo profile create -profile profileprofileprofile[-profile-password-passwordprofile_password] -repository-dbnamerepo_service_name -host-portrepo_port-login-usernamerepo_username -dbnamedb_host[-siddb_host] -password-durerman [-dradditional_addressm -password-atername -password[-drman [-dername -password] [-drman [--password] [--passwordname -atleman [-drst_addressm -password] [--password] [--password-atleman [--atleman [--password] -atime-password-password-password-atername -atleman [--password] [--password] [--password] [--password] -password] -password-password] -password[--atime-domain_address_addressm [--st_addressm -password] -password] -password[--atrman [-drman [--atime-password] -password] [--password[--atime-password] -password] -atime-mail-atime-password[-dr
+
このコマンドの他のオプションは、次のとおりです。

+
[-force]

+

NOTE: SnapManager では、 E メールアドレスが最大 1000 文字までサポートされます。

+
プロファイルを使用して（アーカイブログの個別バックアップを作成するために）データファイルとアーカイブログファイルのバックアップを作成し、データファイルのバックアップの作成に失敗した場合は、データバックアップとアーカイブログのバックアップではなく、処理名としてデータバックアップが送信されます。データファイルおよびアーカイブログファイルのバックアップ処理が成功すると、出力は次のようになります。

+
[listing]
----

Profile Name    : PROF_31
Operation Name 	: Data Backup and Archive Logs Backup
Database SID   	: TENDB1
Database Host 	 : repo1.rtp.org.com
Start Date 	    : Fri Sep 23 13:37:21 EDT 2011
End Date 	      : Fri Sep 23 13:45:24 EDT 2011
Status 	        : SUCCESS
Error messages 	:
----



