---
permalink: unix-administration/concept_considerations_for_cloning_a_database_to_an_alternate_host.html 
sidebar: sidebar 
keywords: clone, host, database, reside, requirement, consideration, alternate, oracle 
summary: データベースが配置されているホスト以外のホストにクローニングを行うには、いくつかの要件を満たす必要があります。 
---
= 代替ホストにデータベースをクローニングする場合の考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データベースが配置されているホスト以外のホストにクローニングを行うには、いくつかの要件を満たす必要があります。

次の表に、ソースホストとターゲットホストのセットアップ要件を示します。

|===
| 設定の前提条件 | 要件 


 a| 
アーキテクチャ
 a| 
ソース・ホストとターゲット・ホストで同じである必要があります



 a| 
オペレーティングシステムおよびバージョン
 a| 
ソース・ホストとターゲット・ホストで同じである必要があります



 a| 
SnapManager for Oracle の略
 a| 
ソース・ホストとターゲット・ホストの両方にインストールされ、実行している必要があります



 a| 
クレデンシャル
 a| 
ユーザがターゲットホストにアクセスできるように設定する必要があります



 a| 
Oracle の場合
 a| 
ソース・ホストとターゲット・ホストに、同じバージョンのソフトウェアをインストールする必要があります。

ターゲット・ホストで Oracle Listener が実行している必要があります。



 a| 
互換性のあるストレージスタック
 a| 
ソース・ホストとターゲット・ホストで同じである必要があります



 a| 
データ・ファイルへのアクセスに使用するプロトコル
 a| 
ソース・ホストとターゲット・ホストで同じである必要があります



 a| 
ボリューム・マネージャ
 a| 
ソース・ホストとターゲット・ホストに、互換性のあるバージョンを設定する必要があります

|===
Automatic Storage Management （ ASM ）データベースをリモートホストにクローニングすることもできます。実行する場合は、リモートホストで ASM インスタンスが実行されていることを確認する必要があります。
