---
permalink: unix-administration/concept_variables_available_in_custom_script_for_restore_operation.html 
sidebar: sidebar 
keywords: snapmanager, context, information, environment, variable, restore, operation 
summary: SnapManager には、実行中のリストア処理に関連する環境変数の形式でコンテキスト情報が表示されます。たとえば、元のホストの名前とリストアされるバックアップのラベルを取得できます。 
---
= リストア処理のタスクスクリプトで使用できる変数
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager には、実行中のリストア処理に関連する環境変数の形式でコンテキスト情報が表示されます。たとえば、元のホストの名前とリストアされるバックアップのラベルを取得できます。

次の表に、スクリプトで使用できる環境変数を示します。

|===
| 変数（ variables ） | 説明 | の形式で入力し 


 a| 
sm_created
 a| 
現在の処理の ID を指定します
 a| 
文字列



 a| 
sm_created ：プロファイル名
 a| 
使用するプロファイルの名前を指定します
 a| 
文字列



 a| 
sm_created
 a| 
データベースのホスト名を指定します
 a| 
文字列



 a| 
sm_created
 a| 
データベースのオペレーティングシステム（ OS ）の所有者を指定します
 a| 
文字列



 a| 
SM_OS_GROUP
 a| 
データベースの OS グループを指定します
 a| 
文字列



 a| 
sm_created タイプ
 a| 
バックアップのタイプを指定します（ online 、 offline 、 auto ）。
 a| 
文字列



 a| 
sm_created ：バックアップラベル
 a| 
バックアップのラベルを指定します
 a| 
文字列



 a| 
sm_created ：バックアップ ID
 a| 
バックアップ ID を指定します
 a| 
文字列



 a| 
sm_created
 a| 
バックアップに使用するプロファイルを指定します
 a| 
文字列



 a| 
sm_created タイプ
 a| 
リカバリ設定情報を指定します
 a| 
文字列



 a| 
sm_created ： volume_restore_mode
 a| 
ボリュームリストア設定を指定します
 a| 
文字列



 a| 
sm_created ：ストレージシステム名
 a| 
ターゲットストレージシステム名を指定します。 * 注：複数のストレージシステムを使用する場合は、ストレージシステム名をカンマで区切って指定する必要があります。
 a| 
文字列



 a| 
sm_created ボリューム名を指定します
 a| 
ターゲットボリューム名を指定します。 * 注：ターゲットボリューム名には、ストレージデバイス名の先頭に sm_created というような名前を付ける必要があります。
 a| 
文字列



 a| 
SM_HOST_FILE_SYSTEM
 a| 
ホスト・ファイルシステムを指定します
 a| 
文字列



 a| 
sm_created 名前
 a| 
Snapshot リストを指定します。 * 注： Snapshot コピー名には、ストレージ・システム名およびボリューム名のプレフィックスを付ける必要があります。Snapshot コピーの名前はカンマで区切って指定します。
 a| 
文字列の配列



 a| 
SM_ASM_DISK_GROUPS です
 a| 
ASM ディスクグループリストを指定します
 a| 
文字列の配列



 a| 
sm_created ディレクトリ
 a| 
アーカイブログディレクトリを指定します。 * 注：アーカイブログが複数のディレクトリにある場合は、これらのディレクトリの名前をカンマで区切って指定します。
 a| 
文字列の配列



 a| 
sm_created ディレクトリ
 a| 
REDO ログディレクトリを指定します * 注： REDO ログが複数のディレクトリに格納されている場合、これらのディレクトリの名前はカンマで区切って指定します。
 a| 
文字列の配列



 a| 
sm_created ファイルディレクトリ
 a| 
制御ファイルのディレクトリを指定します。 * 注： * 制御ファイルが複数のディレクトリにある場合、これらのディレクトリの名前はカンマで区切ります。
 a| 
文字列の配列



 a| 
sm_created ファイルディレクトリ
 a| 
データファイルディレクトリを指定します。 * 注： * データファイルが複数のディレクトリにある場合、これらのディレクトリの名前はカンマで区切ります。
 a| 
文字列の配列

|===