---
permalink: unix-administration/concept_general_layout_and_configuration.html 
sidebar: sidebar 
keywords: recommend, general, database, layout, storage, configuration, avoid, issue, disk, group, file, lun 
summary: 推奨される一般的なデータベースレイアウトとストレージ構成を把握しておくと、ディスクグループ、ファイルタイプ、表領域に関する問題の回避に役立ちます。 
---
= 一般的なデータベースレイアウトとストレージ構成を推奨します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
推奨される一般的なデータベースレイアウトとストレージ構成を把握しておくと、ディスクグループ、ファイルタイプ、表領域に関する問題の回避に役立ちます。

* 複数のタイプの SAN ファイルシステムまたはボリュームマネージャのファイルをデータベースに含めないでください。
+
データベースを構成するすべてのファイルは、同じタイプのファイルシステム上に存在している必要があります。

* SnapManager には 4K ブロックのサイズが複数必要です。
* oratab ファイル内にデータベース・システム ID が含まれています。
+
管理対象の各データベースの oratab ファイル内にエントリが含まれます。SnapManager は、 oratab ファイルに基づいて、使用する Oracle ホームを判別します。

* SnapManager バックアップを Oracle Recovery Manager （ RMAN ）に登録する場合は、 RMAN 対応プロファイルを作成する必要があります。


新しいボリュームベースのリストアまたはディスクグループ全体のリストアを利用する場合は、ファイルシステムとディスクグループに関連する次のガイドラインを考慮してください。

* 複数のデータベースで同じ Automatic Storage Management （ ASM ）ディスクグループを共有することはできません。
* データファイルが含まれるディスクグループに他の種類のファイルを含めることはできません。
* データファイルディスクグループの Logical Unit Number （ LUN ；論理ユニット番号）は、ストレージボリューム内の唯一のオブジェクトである必要があります。


ボリュームを分離する際のいくつかのガイドラインを次に示します。

* ボリュームに格納できるのは、 1 つのデータベースのデータファイルだけです。
* データベースバイナリ、データファイル、オンライン REDO ログファイル、アーカイブ REDO ログファイル、および制御ファイルという分類のファイルごとに、別々のボリュームを使用する必要があります。
* SnapManager では一時データベースファイルがバックアップされないため、一時データベースファイル用に別のボリュームを作成する必要はありません。

