---
permalink: unix-administration/concept_understanding_enabling_or_disabling_of_data_protection_in_profile.html 
sidebar: sidebar 
keywords: enable, disable, data, protection, creating, updating, database, profile, understand 
summary: データベースプロファイルの作成時または更新時にデータ保護を有効または無効にできます。 
---
= プロファイルでのデータ保護の有効化または無効化の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データベースプロファイルの作成時または更新時にデータ保護を有効または無効にできます。

データベース管理者とストレージ管理者は、セカンダリストレージリソース上にあるデータベースの保護されたバックアップを作成するために、次の作業を行います。

|===
| 状況 | 作業 


 a| 
プロファイルを作成または編集します
 a| 
プロファイルを作成または編集するには、次の手順を実行します。

* セカンダリストレージに対するバックアップ保護を有効にする。
* Data ONTAP 7-Mode を使用していて、 Protection Manager をインストールしている場合は、ストレージ管理者またはバックアップ管理者が Protection Manager で作成したポリシーを選択できます。
+
Data ONTAP 7-Mode を使用していて保護が有効になっている場合、 SnapManager はデータベースのデータセットを作成します。データセットは、ストレージセットの集まりと、そのデータに関連付けられている設定情報で構成されます。データセットに関連づけられたストレージ・セットには ' クライアントへのデータのエクスポートに使用されるプライマリ・ストレージ・セット ' および他のストレージ・セットに存在するレプリカとアーカイブのセットが含まれますデータセットは、エクスポート可能なユーザデータを表します。管理者がデータベースの保護を無効にした場合、 SnapManager はデータセットを削除します。

* ONTAP を使用している場合は、作成した SnapMirror 関係または SnapVault 関係に応じて、 _SnapManager_cDOT _ ミラー _ または _SnapManager_cDOT _ ボールト _ ポリシーのいずれかを選択する必要があります。


バックアップの保護を無効にすると、データセットが削除され、このプロファイルのバックアップのリストアまたはクローニングを実行できないことを示す警告メッセージが表示されます。



 a| 
プロファイルを表示します
 a| 
ストレージ管理者が保護ポリシーを実装するためのストレージリソースをまだ割り当てていないため、 SnapManager のグラフィカルユーザインターフェイスと profile show コマンドの出力には、プロファイルが nonConformant と表示されます。



 a| 
Protection Manager 管理コンソールでストレージリソースを割り当て
 a| 
Protection Manager 管理コンソールで、保護されていないデータセットを表示し、プロファイルに関連付けられているデータセットの各ノードにリソースプールを割り当てます。ストレージ管理者は、セカンダリボリュームがプロビジョニングされていて保護関係が初期化されていることを確認します。



 a| 
SnapManager で適合プロファイルを表示します
 a| 
SnapManager では、プロファイルがグラフィカルユーザインターフェイスと profile show コマンドの出力の両方で適合状態に変更されており、リソースが割り当てられていることがデータベース管理者に示されています。



 a| 
バックアップを作成します
 a| 
* フルバックアップを選択します。
* また、バックアップを保護するかどうかを選択し、プライマリの保持クラス（毎時、毎日など）を選択します。
* Data ONTAP 7-Mode を使用していて、 Protection Manager の保護スケジュールを無視してバックアップをセカンダリストレージですぐに保護する場合は、 -protectnow オプションを指定します。
* ONTAP を使用していて、バックアップをセカンダリストレージですぐに保護する場合は、 protect オプションを指定します。
+

NOTE: protectnow オプションは clustered Data ONTAP では使用できません。





 a| 
バックアップを表示します
 a| 
新しいバックアップは、保護のスケジュールに従って表示されますが、まだ保護されていません（ SnapManager インターフェイスおよび backup show コマンドの出力）。保護状態は「保護されていません」と表示されます。



 a| 
バックアップリストを表示する
 a| 
ストレージ管理者がバックアップがセカンダリ・ストレージにコピーされたことを確認すると ' SnapManager はバックアップ保護状態を Not protected から Protected に変更します

|===