---
permalink: unix-administration/concept_what_user_authentication_is.html 
sidebar: sidebar 
keywords: addition, role-based, access, control, rbac, snapmanager, authenticate, operating, system, os 
summary: SnapManager では、 Role-Based Access Control （ RBAC ；ロールベースアクセス制御）に加えて、 SnapManager サーバが実行されているホストでオペレーティングシステム（ OS ）ログインを使用してユーザを認証します。ユーザ認証は、処理時にパスワードプロンプトを使用して有効にするか、 smo credential set コマンドを使用して有効にできます。 
---
= ユーザ認証とは
:icons: font
:imagesdir: ../media/


[role="lead"]
ロールベースアクセス制御（ RBAC ）に加えて、 SnapManager では、 SnapManager サーバが実行されているホストでオペレーティングシステム（ OS ）ログインを使用してユーザを認証します。ユーザ認証は、処理時にパスワードプロンプトを使用して有効にするか、 smo credential set コマンドを使用して有効にできます。

ユーザ認証の要件は、処理を実行する場所によって異なります。

* SnapManager クライアントが SnapManager ホストと同じサーバ上にある場合は、 OS のクレデンシャルによって認証されます。
+
SnapManager サーバが実行されているホストにすでにログインしているため、パスワードの入力は求められません。

* SnapManager クライアントと SnapManager サーバが異なるホスト上にある場合、 SnapManager は両方の OS クレデンシャルを使用してユーザを認証する必要があります。
+
SnapManager ユーザクレデンシャルキャッシュに OS クレデンシャルを保存していない場合、 SnapManager は処理のためのパスワードの入力を求めます。smo credential set -host コマンドを入力した場合は、 SnapManager クレデンシャルキャッシュファイルに OS クレデンシャルを保存するため、 SnapManager は処理のためのパスワードの入力を求めません。



SnapManager サーバで認証されている場合は、有効なユーザとみなされます。すべての処理の実効ユーザは、処理が実行されるホストの有効なユーザアカウントである必要があります。たとえば、クローニング処理を実行する場合は、クローンのデスティネーションホストにログインできる必要があります。


NOTE: SnapManager for Oracle では、 LDAP や ADS などの中央 Active Directory サービスで作成されたユーザの許可が失敗することがあります。認証が失敗しないようにするには、設定可能な auth.disableServerAuthorization を true に設定する必要があります。

実効ユーザとして、次の方法でクレデンシャルを管理できます。

* 必要に応じて、 SnapManager ユーザクレデンシャルファイルにユーザクレデンシャルを格納するように SnapManager を設定することができます。
+
デフォルトでは、 SnapManager にはホストクレデンシャルは格納されません。たとえば、リモートホストへのアクセスを必要とするカスタムスクリプトがある場合などに、この変更が必要になることがあります。リモートクローニング処理は、リモートホストのユーザのログインクレデンシャルが必要な SnapManager 処理の例です。SnapManager がユーザ・ホストのログイン・クレデンシャルを SnapManager ユーザ・クレデンシャルのキャッシュに保存するようにするには、 smo .config ファイルで host.credentials" プロパティを true に設定します。

* リポジトリへのユーザ・アクセスを許可できます。
* プロファイルへのユーザアクセスを許可できます。
* すべてのユーザクレデンシャルを表示できます。
* すべてのリソース（ホスト、リポジトリ、およびプロファイル）について、ユーザのクレデンシャルを消去できます。
* 個々のリソース（ホスト、リポジトリ、およびプロファイル）のクレデンシャルを削除できます。

