---
permalink: unix-administration/concept_restores_of_protected_backups_overview.html 
sidebar: sidebar 
keywords: restore, backup, data, secondary, primary, storage, overview, protect, primary, lun 
summary: セカンダリストレージからプライマリストレージにバックアップデータをリストアする際に使用するリストア方式を選択できます。 
---
= 保護されたバックアップのリストアの概要
:icons: font
:imagesdir: ../media/


[role="lead"]
セカンダリストレージからプライマリストレージにバックアップデータをリストアする際に使用するリストア方式を選択できます。

次の表に、セカンダリストレージからバックアップをリストアする際に使用できるさまざまなシナリオと方法を示します。

|===
| リストア先 | 説明 


 a| 
プライマリストレージに直接バックアップします
 a| 
データの保護に使用したネットワーク経由で、セカンダリストレージシステムからプライマリストレージシステム上の元の場所に直接データを返します。

SnapManager では、可能なかぎり直接ストレージ方式を使用します。この方法は、データが Storage Area Network （ SAN ；ストレージエリアネットワーク）上のファイルシステムにある場合、および次のいずれかの条件に該当する場合は実行できません。

* 他のデータベース以外のファイルは、同じファイルシステムにリストアされません。
* リストア対象のファイルシステム内の制御ファイルとデータファイルの Snapshot コピーは、別のタイミングで作成されています。
* LUN はボリュームグループに含まれていますが、同じボリュームグループ内の他の LUN はリストアされていません。




 a| 
ホストに直接接続します
 a| 
セカンダリストレージシステム上のデータをクローニングして、ホストにクローンデータをマウントします。データがクローニングされてマウントされると、 SnapManager によって元の場所にコピーされます。



 a| 
ストレージまたはホストに間接的に接続します
 a| 
データの保護とホストへの新しいストレージのマウントに使用したネットワークを介して、セカンダリストレージシステムからプライマリシステム上の新しい場所にデータを返します。データが返されてマウントされると、 SnapManager は元の場所にデータをコピーします。間接ストレージを使用する場合、データを取得するのに時間がかかることがあります。

SnapManager では、まずプライマリホスト上のスクラッチボリュームにデータをコピーし、次に SnapManager でデータベースのリストアとリカバリを実行します。スクラッチデータが自動的に削除されるかどうかは、使用するプロトコルによって異なります。

* SAN の場合、 SnapManager は返されたデータを削除します。
* Network-Attached Storage （ NAS ；ネットワーク接続型ストレージ）の場合、 SnapManager は返された qtree の内容を削除しますが、 qtree 自体は削除しません。qtree を削除するには、 UNIX の rmdir コマンドを使用して、スクラッチ・ボリュームをマウントし、 qtree を削除します。


|===
データをストレージに直接戻すことができない場合、 SnapManager はデータをホストに直接返すことも、ストレージまたはホストに間接的に返すこともできます。方法は、組織がセカンダリストレージへの直接接続を許可するか、ストレージネットワーク経由でデータをコピーする必要があるかを制御するポリシーによって異なります。このポリシーを管理するには、 smo .config ファイルに構成情報を設定します。

* 関連情報 *

xref:reference_snapmanager_configuration_parameters.adoc[SnapManager の設定パラメータ]
