---
permalink: unix-administration/concept_workflow_summary_for_local_and_secondary_database_backup.html 
sidebar: sidebar 
keywords: dba, snapmanager, storage, administrator, netapp, management, console, data, protection, capability, backup, database, workflow, summary 
summary: この例では、 DBA （ SnapManager を使用）とストレージ管理者（ネットアップ管理コンソールのデータ保護機能を使用）が、対象データベースのローカルバックアップとセカンダリバックアップ（保護されたバックアップ）の設定作業をコーディネートしています。 
---
= ローカルおよびセカンダリデータベースバックアップのワークフローの概要
:icons: font
:imagesdir: ../media/


[role="lead"]
この例では、 DBA （ SnapManager を使用）とストレージ管理者（ネットアップ管理コンソールのデータ保護機能を使用）が、対象データベースのローカルバックアップとセカンダリバックアップ（保護されたバックアップ）の設定作業をコーディネートしています。

実行されるアクションの順序は、次のように要約されます。

* * セカンダリ・リソース・プール構成 *
+
ストレージ管理者は、 NetApp Management Console のデータ保護機能を使用して、セカンダリサイトのストレージシステムのリソースプールを設定します。このリソースプールには、給与データベースのバックアップを格納できます。

* * セカンダリ・バックアップのスケジュール設定 *
+
ストレージ管理者は、 NetApp Management Console のデータ保護機能を使用して、セカンダリバックアップスケジュールを設定します。

* * 保護ポリシーの設定 *
+
ストレージ管理者は、 NetApp Management Console のデータ保護機能を使用して、ターゲットデータベースのセカンダリバックアップ保護ポリシーを設定します。保護ポリシーには、バックアップ保護を実装する保護のベースタイプ（バックアップ、ミラー、またはその両方）とプライマリデータ、セカンダリ、および場合によってはターシャリストレージノードの名前保持ポリシーが含まれます。

* * データベース・プロファイルの構成と保護ポリシーの割り当て *
+
DBA は、 SnapManager を使用して、セカンダリバックアップをサポートするターゲット・データベースのプロファイルを作成または編集します。プロファイルの設定中に DBA は次のことを行います

+
** セカンダリストレージに対するバックアップ保護を有効にします。
** このプロファイルには、 NetApp Management Console のデータ保護機能で作成されて取得された新しい保護ポリシーを割り当てます。
+
保護ポリシーを割り当てると、ターゲットデータベースが部分的にプロビジョニングされた状態で自動的に含まれますが、 NetApp Management Console のデータ保護機能データセットに適合しません。データセットの設定が完全にプロビジョニングされると、ターゲットデータベースをセカンダリストレージにバックアップできるようになります。

+
データセット名では、「 smo _hostname_databasename 」という構文を使用します。この構文は、「 smo_payroll.techco.com_paydb" 」に変換されます。



* * セカンダリおよびターシャリストレージプロビジョニング *
+
ストレージ管理者は、 NetApp Management Console のデータ保護機能を使用して、リソースプールを割り当てて、セカンダリストレージノードおよび場合によってはターシャリストレージノードをプロビジョニングします（割り当てられた保護ポリシーに 3 次ストレージノードが指定されている場合）。

* * ローカルストレージ上のバックアップ *
+
DBA は、 SnapManager で保護を有効にしたプロファイルを開き、ローカルストレージへのフルバックアップを作成します。新しいバックアップは、保護のスケジュールに従って SnapManager に表示されますが、まだ保護されていません。

* * 二次バックアップの確認 *
+
バックアップは保護が有効なプロファイルに基づいているため、保護ポリシーのスケジュールに従ってセカンダリに転送されます。データベース管理者は、 SnapManager を使用して、セカンダリ・ストレージへのバックアップの転送を確認します。バックアップがセカンダリストレージにコピーされると、 SnapManager はバックアップの保護状態を「 Not protected 」から「 Protected 」に変更します。


