---
permalink: unix-administration/reference_the_smosmsapcredential_delete_command.html 
sidebar: sidebar 
keywords: command, delete, user, credential, particular, secure, resource, smo 
summary: このコマンドは、特定のセキュアリソースのユーザクレデンシャルを削除します。 
---
= smo credential delete コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このコマンドは、特定のセキュアリソースのユーザクレデンシャルを削除します。



== 構文

[listing]
----

        smo credential delete
\[-host -name host_name
-username username\] \|
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port\] \|
\[-profile
-name profile_name\]
[-quiet | -verbose]
----


== パラメータ

* * - ホスト名 *
+
SnapManager が実行されているホストサーバの名前を指定します。

+
host パラメータには、次のオプションがあります。

+
** -name host_name ：パスワードを削除するホストの名前を指定します。
** -username user_name ：ホスト上のユーザ名を指定します。


* * -repository -dbname *
+
プロファイルが格納されたデータベースの名前を指定します。グローバル名または SID を使用します。

+
repository パラメータには、次のオプションが含まれます。

+
** -dbnamerepo_service_name ：プロファイルを格納するデータベースの名前を指定します。グローバル名または SID を使用します。
** -host repo_host ：リポジトリ・データベースが稼働しているホスト・サーバの名前または IP アドレスを指定します。
** -login-username repo_username ：リポジトリが格納されたデータベースにアクセスするために必要なユーザ名を指定します。
** -port repo_port ：リポジトリが格納されているデータベースへのアクセスに使用する TCP ポート番号を指定します。


* * -profile-name profile_name *
+
データベースに関連付けられたプロファイルを指定します。

+
profile パラメータには、次のオプションが含まれています。

+
** -name profilename ：パスワードを削除するプロファイルの名前を指定します。


* * - Quiet *
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* * -verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。





== コマンドの例

次に、プロファイルのクレデンシャルを削除する例を示します。

[listing]
----
smo credential delete -profile -name user1 -verbose
----
[listing]
----
SMO-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----
次に、リポジトリのクレデンシャルを削除する例を示します。

[listing]
----
smo credential delete -repository -dbname SMOREPO -host Host2
-login -username user1 -port 1521
----
[listing]
----
SMO-20023 [INFO ]: Deleted repository credentials for "user1@SMOREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----
次に、ホストのクレデンシャルを削除する例を示します。

[listing]
----
smo credential delete -host -name Host2
----
[listing]
----
SMO-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----
* 関連情報 *

xref:task_deleting_credentials_for_individual_resources.adoc[個々のリソースのクレデンシャルを削除する]
