---
permalink: unix-administration/reference_the_smosmsap_notification_set_command.html 
sidebar: sidebar 
keywords: notification, set, command, configure, mail, server, smo, email, sender, email 
summary: 通知セットコマンドを使用してメールサーバを設定できます。 
---
= smo notification set コマンド
:icons: font
:imagesdir: ../media/


[role="lead"]
通知セットコマンドを使用してメールサーバを設定できます。



== 構文

[listing]
----

        smo notification set
-sender-email email_address
-mailhost mailhost
-mailport mailport
[-authentication
-username username
-password password]
-repository
-dbname repo_service_name
-port repo_port]
-host repo_host
-login -username repo_username
[-quiet | -verbose]
----


== パラメータ

* * -sender - email email_address *
+
E メールアラートの送信元の E メールアドレスを指定します。SnapManager 3.2 for Oracle では、 E メールアドレスのドメイン名を指定する際にハイフン（ - ）を使用できます。たとえば、送信者の E メールアドレスを -sender-email07lbfmdatacenter@continental-corporation.com と指定できます。

* * -mailhost mailhost*
+
E メール通知を処理するホストサーバの名前または IP アドレスを指定します。

* *-mailport mailport*
+
メールサーバのポート番号を指定します。

* * -authentication-username username USERNAME - password password*
+
E メールアドレスの認証の詳細を指定します。ユーザ名とパスワードを指定する必要があります。

* * - リポジトリ *
+
リポジトリ・データベースの詳細を指定します。

* * -port repo_port *
+
リポジトリデータベースへのアクセスに使用する TCP （ Transmission Control Protocol ）ポート番号を指定します。

* * -dbname repo_service_name *
+
リポジトリ・データベースの名前を指定します。グローバル名またはシステム ID を使用できます。

* * -host repo_host *
+
リポジトリ・データベースが置かれているホストの名前または IP アドレスを指定します。

* * - ログイン *
+
リポジトリ・ログインの詳細を指定します。これはオプションです。指定しない場合、 SnapManager はデフォルトで OS 認証接続モードになります。

* * -username repo_username *
+
リポジトリ・データベースへのアクセスに必要なユーザ名を指定します。

* * - Quiet *
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* * -verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。





== 例

次の例では、メールサーバを設定します。

[listing]
----
smo notification set -sender-email admin@org.com -mailhost hostname.org.com -mailport 25 authentication -username davis -password davis -repository -port 1521 -dbname SMOREPO -host hotspur
-login -username grabal21 -verbose
----