---
permalink: unix-administration/reference_the_smosmsapbackup_mount_command.html 
sidebar: sidebar 
keywords: run, backup, mount, command, perform, recover, operation, external, tool, smo 
summary: 外部ツールを使用してリカバリ処理を実行するには、 backup mount コマンドを実行してバックアップをマウントします。 
---
= smo backup mount コマンド
:icons: font
:imagesdir: ../media/


[role="lead"]
外部ツールを使用してリカバリ処理を実行するには、 backup mount コマンドを実行してバックアップをマウントします。



== 構文

[listing]
----

        smo backup mount
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id id\]
[-host  host]
\[-from-secondary \{-copy-id id\}\]
\[-dump\]
[-quiet | -verbose]
----


== パラメータ

* * -profile profile_name *
+
マウントするバックアップに関連付けられたプロファイルを指定します。プロファイルには、データベースの識別子およびその他のデータベース情報が含まれています。

* *-id GUID*
+
指定した GUID を持つバックアップをマウントします。GUID はバックアップを作成するときに SnapManager によって生成されます。各バックアップの GUID を表示する場合は、 smo backup list コマンドを使用します。

* * - ラベルラベル *
+
指定したラベルを持つバックアップをマウントします。

* *-data*
+
データファイルを指定します。

* *-archivelogs*
+
アーカイブログファイルを指定します。

* * -from-ssecond-copy-id ID *
+
セカンダリストレージからバックアップをマウントします。このオプションを指定しない場合、 SnapManager はプライマリストレージからバックアップをマウントします。このオプションは、バックアップが解放されている場合に使用できます。

+
from-secondary オプションを指定した場合は、必ず -copy-id オプションを指定する必要があります。セカンダリストレージシステムに複数のバックアップがある場合は、 -copy-id オプションを使用して、セカンダリストレージにバックアップのマウントに使用するバックアップコピーを指定します。

+

NOTE: Data ONTAP 7-Mode を使用している場合は、 -copy-id オプションに有効な値を指定する必要があります。ただし、 clustered Data ONTAP を使用している場合は、 -copy-id オプションは不要です。

* * - ホストホストホスト *
+
バックアップをマウントするホストを指定します。

* * -dump*
+
マウント処理が成功したか失敗したあとにダンプファイルを収集します。

* * - Quiet *
+
コンソールにエラーメッセージのみを表示します。デフォルト設定では、エラーおよび警告メッセージが表示されます。

* * -verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。




NOTE: このコマンドは、 Oracle Recovery Manager （ RMAN ）などの外部ツールを使用する場合にのみ使用する必要があります。smo backup restore コマンドを使用してバックアップをリストアする場合は、バックアップのマウントが SnapManager によって自動的に処理されます。このコマンドを実行すると、 Snapshot コピーがマウントされているパスのリストが表示されます。このリストは、 -verbose オプションを指定した場合のみ表示されます。



== 例

次に、バックアップをマウントする例を示します。

[listing]
----
smo backup mount -profile SALES1 -label full_backup_sales_May -verbose
SMO-13046 [INFO ]: Operation GUID 8abc013111b9088e0111b908a7560001 starting on Profile SALES1
SMO-08052 [INFO ]: Beginning to connect mount(s) [/mnt/ssys1/logs, /mnt/ssys1/data] from logical snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001.
SMO-08025 [INFO ]: Beginning to connect mount /mnt/ssys1/logs from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_logs.
SMO-08027 [INFO ]: Finished connecting mount /mnt/ssys1/logs from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_logs.
SMO-08025 [INFO ]: Beginning to connect mount /mnt/ssys1/data from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_data.
SMO-08027 [INFO ]: Finished connecting mount /mnt/ssys1/data from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_data.
SMO-08053 [INFO ]: Finished connecting mount(s) [/mnt/ssys1/logs, /mnt/ssys1/data] from logical snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001.
SMO-13037 [INFO ]: Successfully completed operation: Backup Mount
SMO-13048 [INFO ]: Operation Status: SUCCESS
SMO-13049 [INFO ]: Elapsed Time: 0:01:00.981
Operation Id [8abc013111b9088e0111b908a7560001] succeeded.
----
* 関連情報 *

xref:task_mounting_backups.adoc[バックアップのマウント]
