---
permalink: unix-administration/reference_the_smosmsapclone_create_command.html 
sidebar: sidebar 
keywords: run, clone, create, command, backed-up, database, primary, secondary, storage 
summary: clone create コマンドを実行して、バックアップされたデータベースのクローンを作成できます。バックアップはプライマリストレージまたはセカンダリストレージからクローニングできます。 
---
= smo clone create コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
clone create コマンドを実行して、バックアップされたデータベースのクローンを作成できます。バックアップはプライマリストレージまたはセカンダリストレージからクローニングできます。



== 構文

[listing]
----

        smo clone create
-profile profile_name
[-backup-id backup_guid \| -backup-label backup_label_name \| -current\]
-newsid new_sid
\[-host target_host\]
[-label clone_label]
\[-comment string\]
-clonespec full_path_to_clonespec_file
\[-asminstance -asmusername asminstance_username  -asmpassword asminstance_password\]]
\[-syspassword syspassword\]
\[-reserve \{yes \| no \| inherit\}\]
\[-from-secondary \{-copy-id id\}\]
\[-no-resetlogs \| -recover-from-location path1 \[, path2\]\]\[-taskspec taskspec\]
\[-dump\]
\[-quiet \| -verbose\]
----


== パラメータ

* * - プロファイル名 *
+
クローニングするデータベースを指定します。プロファイルには、データベースの識別子およびその他のデータベース情報が含まれています。

* * -backup-id GUID*
+
指定した GUID を持つバックアップをクローニングします。GUID はバックアップを作成するときに SnapManager によって生成されます。各バックアップの GUID を表示する場合は、 smo backup list -verbose コマンドを使用します。

* * -backup-label backup_label_name *
+
指定したラベル名を持つバックアップをクローニングするように指定します。

* * - 現在 *
+
データベースの現在の状態からバックアップおよびクローンを作成するように指定します。

+

NOTE: データベースが NOARCHIVELOG モードになっている場合、 SnapManager はオフラインバックアップを作成します。

* *-newsid new_sid *
+
クローニングされたデータベースに新しい一意の Oracle システム識別子を指定します。システム ID の値は 8 文字以内で指定します。Oracle では、同じホスト上で同じシステム識別子を持つ 2 つのデータベースを同時に実行することはできません。

* * -host target_host *
+
クローンを作成するホストを指定します。

* * -label clone_label *
+
クローンのラベルを指定します。

* * -comment string*
+
このクローンについて説明するオプションのコメントを指定します。文字列は一重引用符で囲む必要があります。

+

NOTE: 一部のシェルでは引用符が削除されます。ご使用のシェルに当てはまる場合は、引用符をバックスラッシュ（ \ ）でエスケープする必要があります。たとえば、次のように入力する必要があります。「 This is a comment\ 」

* * -clonespec full_path_to_clonespec_file *
+
クローン仕様 XML ファイルのパスを指定します。相対パス名または絶対パス名を指定できます。

* *-asminstance*
+
ASM インスタンスへのログインに使用するクレデンシャルを指定します。

* *-asmusername asminstance_username*
+
ASM インスタンスへのログインに使用するユーザ名を指定します。

* *-asmpassword asminstance_password*
+
ASM インスタンスへのログインに使用するパスワードを指定します。

* *-syspassword syspassword*
+
sys 特権ユーザのパスワードを指定します。

+

NOTE: 指定されたデータベースクレデンシャルが sys 特権ユーザに対して同じでない場合は、 sys 特権ユーザのパスワードを指定する必要があります。

* * - 予約 *
+
reserve オプションを yes に設定すると、新しいクローン・ボリュームのためのボリューム・ギャランティ・スペース・リザベーションがオンになります。reserve オプションを no に設定すると、新しいクローン・ボリュームのためのボリューム・ギャランティ・スペース・リザベーションがオフになります。reserve オプションを inherit に設定すると、新しいクローンは親の Snapshot コピーのスペース・リザベーション特性を継承します。デフォルト設定は no です

+
次の表に、クローニング方法、およびクローン作成処理とその -reserve オプションに対する影響を示します。LUN は、どちらの方法でもクローニングできます。

+
|===


| クローニング方法 | 説明 | 結果 


 a| 
 LUN cloning a| 
 A new clone LUN is created within the same volume. a| 
 When the -reserve option for a LUN is set to yes, space is reserved for the full LUN size within the volume.


 a| 
 Volume cloning a| 
 A new FlexClone is created, and the clone LUN exists within the new clone volume. Uses the FlexClone technology. a| 
 When the -reserve option for a volume is set to yes, space is reserved for the full volume size within the aggregate.
[+]

|===
* * -from-ssecondary [-copy-idcopy_id]*
+
セカンダリストレージで保護されているバックアップのコピーを SnapManager でクローニングするように指定します。このオプションを指定しない場合、 SnapManager はプライマリストレージからコピーをクローニングします。

+
from-secondary オプションを指定した場合は、必ず -copy-id オプションを指定する必要があります。セカンダリストレージシステムに複数のバックアップがある場合は、 -copy-id オプションを使用して、セカンダリストレージ上でクローニングに使用するバックアップコピーを指定します。

+

NOTE: Data ONTAP 7-Mode を使用している場合は、 -copy-id オプションに有効な値を指定する必要があります。ただし、 clustered Data ONTAP を使用している場合は、 -copy-id オプションは不要です。

* *-no-resetlogs*
+
クローン作成時に resetlogs でデータベースを開かずに、 DBNEWID ユーティリティを実行してデータベースのリカバリをスキップするように指定します。

* * -recovery-from-location*
+
アーカイブログバックアップの外部アーカイブログの場所を指定します。 SnapManager は外部の場所からアーカイブログファイルを取得し、クローニングに使用します。

* *-taskspec*
+
クローン処理の前処理アクティビティまたは後処理アクティビティのタスク仕様 XML ファイルを指定します。タスク仕様 XML ファイルの完全なパスを指定する必要があります。

* * -dump*
+
クローン作成処理のあとにダンプファイルを収集するように指定します。

* * - Quiet *
+
コンソールにエラーメッセージのみを表示します。デフォルト設定では、エラーおよび警告メッセージが表示されます。

* * -verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。





== 例

次に、このクローン用に作成されたクローン仕様を使用して、バックアップをクローニングする例を示します。

[listing]
----
smo clone create -profile SALES1 -backup-label full_backup_sales_May -newsid
CLONE -label sales1_clone -clonespec /opt/<path>/smo/clonespecs/sales1_clonespec.xml
----
[listing]
----
Operation Id [8abc01ec0e794e3f010e794e6e9b0001] succeeded.
----
* 関連情報 *

xref:task_creating_clone_specifications.adoc[クローン仕様を作成しています]

xref:task_cloning_databases_from_backups.adoc[バックアップからデータベースをクローニングする]
