---
permalink: unix-administration/reference_the_smosmsap_history_list_command.html 
sidebar: sidebar 
keywords: command, enable, list, history, detail, snapmanager, operation, smo 
summary: このコマンドを使用すると、 SnapManager 処理の履歴の詳細のリストを表示できます。 
---
= smo history list コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このコマンドを使用すると、 SnapManager 処理の履歴の詳細のリストを表示できます。



== 構文

[listing]
----

        smo history list
-profile \{-name profile_name \[profile_name1, profile_name2\] \| -all
-repository
-login \[-password repo_password\]
-username repo_username
-host repo_host
-dbname repo_dbname
-port repo_port}
-operation \{-operations operation_name \[operation_name1, operation_name2\] \| -all\}
\[-delimiter character\]
\[-quiet \| -verbose\]
----


== パラメータ

* * -profile profile *
+
プロファイルの名前を指定します。この名前には 30 文字まで使用でき、ホスト内で一意である必要があります。

* * - リポジトリ *
+
repository のあとに続くオプションは、プロファイルが格納されるデータベースの詳細を指定します。

* * -dbname repo_dbname *
+
プロファイルが格納されたデータベースの名前を指定します。グローバル名または SID を使用します。

* * -host repo_host *
+
リポジトリ・データベースが稼働しているホスト・コンピュータの名前または IP アドレスを指定します。

* * - ログイン *
+
リポジトリ・ログインの詳細設定を開始します。

* * -username repo_username *
+
リポジトリが格納されたデータベースにアクセスするために必要なユーザ名を指定します。

* * -port repo_port *
+
リポジトリが格納されたデータベースへのアクセスに使用する TCP ポート番号を指定します。

* * -operation ｛ operationsoperation_name [operation_name1 、 operation_name2 ]|-all *
+
履歴を設定する SnapManager 処理を指定します。

* * - Quiet *
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* * -verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。





== コマンドの例

[listing]
----

          smo  history list -profile -name PROFILE1 -operation -operations backup -verbose
----