---
permalink: unix-administration/reference_the_smosmsapprofile_update_command.html 
sidebar: sidebar 
keywords: run, profile, update, command, information, existing, profile, smo 
summary: profile update コマンドを実行して、既存のプロファイルの情報を更新できます。 
---
= smo profile update コマンド
:icons: font
:imagesdir: ../media/


[role="lead"]
profile update コマンドを実行して、既存のプロファイルの情報を更新できます。



== 構文

[listing]
----

        smo profile update
-profile profile
\[-new-profile new_profile_name\]
\[-profile-password profile_password\]
[-database
-dbname db_dbname
-host db_host
\[-sid db_sid\]
[-login
\[-username db_username -password db_password -port db_port\]
 \[-asminstance -asmusername asminstance_username  -asmpassword asminstance_password\]]
[\{-rman  \{-controlfile \| \{\{-login
-username  rman_username
-password  rman_password \}
\[-tnsname  tnsname\]\}\}\} \|
-remove-rman\]
-osaccount osaccount
-osgroup osgroup
[-retain
\[-hourly \[-count n\] \[-duration m\]\]
\[-daily \[-count n\] \[-duration m\]]
\[-weekly \[-count n\] \[-duration m\]]
\[-monthly \[-count n\] \[-duration m\]]]]
-comment comment
-snapname-patternpattern
[-protect \[-protection-policy policy_name\] \| \[-noprotect\]]
[-summary-notification]
[-notification
\[-success
-email email_address1,email_address2
-subject subject_pattern\]
\[-failure
-email email_address1,email_address2
-subject subject_pattern]
[-separate-archivelog-backups
-retain-archivelog-backups
-hours  hours |
-days days |
-weeks weeks |
-months months
[-protect \[-protection-policy policy_name\] \| \[-noprotect\]]
[-include-with-online-backups \| -no-include-with-online-backups]]
[-dump]
\[-quiet \| -verbose\]
----


== パラメータ

プロファイルに保護ポリシーが設定されている場合は、 SnapManager を使用してポリシーを変更することはできません。ポリシーは Protection Manager のコンソールを使用して変更する必要があります。

* * -profile profile *
+
プロファイルの名前を指定します。この名前には 30 文字まで使用でき、ホスト内で一意である必要があります。

* * -profile-password profile_password * を入力します
+
プロファイルのパスワードを指定します。

* * -new-profile new_profile_name *
+
プロファイルに指定できる新しい名前を指定します。

* * -database *
+
プロファイルに記述されるデータベースの詳細を指定します。このデータベースに対してバックアップ、リストアなどが実行されます。

* * -dbname db_dbname *
+
プロファイルに記述されるデータベースの名前を指定します。グローバル名またはシステム ID を使用できます。

* * -host db_host *
+
データベースが稼働しているホスト・コンピュータの名前または IP アドレスを指定します。

* *-sid db_sid *
+
プロファイルに記述されるデータベースのシステム識別子を指定します。デフォルトでは、 SnapManager はデータベース名をシステム識別子として使用します。システム ID がデータベース名と異なる場合は、 -sid オプションを使用して指定する必要があります。

+
たとえば、 Oracle Real Application Clusters （ RAC ）を使用している場合は、 SnapManager の実行元 RAC ノード上の RAC インスタンスの SID システム識別子を指定する必要があります。

* * - ログイン *
+
リポジトリ・ログインの詳細を指定します。

* * -username repo_username *
+
リポジトリ・データベースへのアクセスに必要なユーザ名を指定します。

* * -port repo_port *
+
リポジトリ・データベースへのアクセスに必要な TCP ポート番号を指定します。

* * -database *
+
プロファイルに記述されるデータベースの詳細を指定します。このデータベースに対してバックアップ、リストア、またはクローニングが実行されます。

* * -dbname db_dbname *
+
プロファイルに記述されるデータベースの名前を指定します。グローバル名またはシステム ID を使用できます。

* * -host db_host *
+
データベースが稼働しているホスト・コンピュータの名前または IP アドレスを指定します。

* * - ログイン *
+
データベース・ログインの詳細を指定します。

* * -username repo_username *
+
プロファイルに記述されるデータベースにアクセスするために必要なユーザ名を指定します。

* * -password db_password *
+
プロファイルに記述されるデータベースにアクセスするために必要なパスワードを指定します。

* * -port db_port *
+
プロファイルに記述されるデータベースへのアクセスに必要な TCP ポート番号を指定します。

* *-asminstance*
+
Automatic Storage Management （ ASM ）インスタンスへのログインに使用するクレデンシャルを指定します。

* *-asmusername asminstance_username*
+
ASM インスタンスへのログインに使用するユーザ名を指定します。

* *-asmpassword asminstance_password*
+
ASM インスタンスへのログインに使用するパスワードを指定します。

* * - rman*
+
SnapManager が Oracle Recovery Manager （ RMAN ）を使用してバックアップをカタログ化するために使用する詳細情報を指定します。

* * -controlfile *
+
カタログではなくターゲットのデータベース制御ファイルを RMAN リポジトリとして指定します。

* * - ログイン *
+
RMAN ログインの詳細を指定します。

* * -password rman_password*
+
RMAN カタログへのログインに使用するパスワードを指定します。

* * -username rman_username *
+
RMAN カタログへのログインに使用するユーザ名を指定します。

* *-tnsname tnsname *
+
tnsname 接続名を指定します（ tnsname.ora ファイルで定義されています）。

* *-remove-rman*
+
プロファイルで RMAN を削除するように指定します。

* * -osaccount osaccount *
+
Oracle データベースのユーザアカウントの名前を指定します。SnapManager はこのアカウントを使用して、起動やシャットダウンなどの Oracle 処理を実行します。通常は、 Oracle など、ホスト上で Oracle ソフトウェアを所有しているユーザがこれに該当します。

* * -osgroup osgroup *
+
Oracle アカウントに関連付けられた Oracle データベースグループの名前を指定します。

* * -retain [-hourly [-countn] [-duration m] [-daily [-duration n] [-duration n] [-duration m]] [-weekly [-count n] [-duration n] [-duration m]] [-monthly [-monthly ] [-duration n] ] *
+
バックアップの保持クラス（毎時、毎日、毎週、毎月）を指定します。

+
各保持クラスについて、保持数または保持期間、あるいはその両方を指定できます。期間はクラスの単位で指定します（たとえば、時間単位の場合は時間単位、日単位の場合は日単位）。たとえば、日次バックアップの保持期間として 7 のみを指定した場合、 SnapManager ではプロファイルの日次バックアップの数が制限されません（保持数が 0 であるため）。ただし、 SnapManager では、 7 日前に作成された日次バックアップが自動的に削除されます。

* * -comment comment*
+
プロファイルのコメントを指定します。

* * - snapname - pattern pattern パターン *
+
Snapshot コピーの命名パターンを示します。すべての Snapshot コピー名に、可用性の高い処理用の HAOPS などのカスタムテキストを含めることもできます。Snapshot コピーの命名パターンは、プロファイルの作成時、またはプロファイルの作成後に変更できます。更新後のパターンは、まだ実行されていない Snapshot コピーにのみ適用されます。存在する Snapshot コピーには、前の snapname パターンが保持されます。パターンテキストでは、複数の変数を使用できます。

* *-protect [-protection-policypolicy_name] | [-noprotection] *
+
バックアップをセカンダリストレージで保護するかどうかを指定します。

+

NOTE: protection-policy を指定しないと、データセットに保護ポリシーが設定されません。profile-protect を指定し、 -protection-policy を設定しない場合、プロファイルの作成時に bysmo profile update コマンドをあとで設定するか、 Protection Manager のコンソールを使用してストレージ管理者が設定します。

+
noprotect オプションは、プロファイルをセカンダリ・ストレージで保護しないように指定します。

* *-summary-notification*
+
既存のプロファイルでサマリー E メール通知を有効にします。

* * -notification [-success -email e-mail address1, e-mail address2-subject_pattern]*
+
既存のプロファイルに関する E メール通知を有効にして、 SnapManager 処理が成功したときに受信者から E メールが受信されるようにします。E メールアラートの送信先となる 1 つまたは複数の E メールアドレスと、既存のプロファイルの E メール件名のパターンを入力する必要があります。

+
件名のテキストは、プロファイルの更新中に変更することも、カスタムの件名テキストを含めることもできます。更新された件名は、送信されない E メールにのみ適用されます。E メールの件名にはいくつかの変数を使用できます。

* * -notification [-failure-email e-mail address1, e-mail address2-subject_pattern]*
+
既存のプロファイルに関する E メール通知を有効にして、 SnapManager 処理が失敗したときに受信者に E メールを送信できるようにします。E メールアラートの送信先となる 1 つまたは複数の E メールアドレスと、既存のプロファイルの E メール件名のパターンを入力する必要があります。

+
件名のテキストは、プロファイルの更新中に変更することも、カスタムの件名テキストを含めることもできます。更新された件名は、送信されない E メールにのみ適用されます。E メールの件名にはいくつかの変数を使用できます。

* *-Separe-archivelog -bbackups * を実行します
+
アーカイブログバックアップとデータファイルバックアップを分離します。これは、プロファイルの作成時に指定できるオプションのパラメータです。このオプションを使用してバックアップを分けたあとで、データファイルのみのバックアップまたはアーカイブログのみのバックアップを作成できます。

* *-retain-archivelog -bbackups -hours | -daysdays | -weeksweeks | -monthsmonths *
+
アーカイブログの保持期間（毎時、毎日、毎週、毎月）に基づいてアーカイブログのバックアップを保持するように指定します。

* *-protect [-protection-policypolicy_name] |-nobprotect *
+
アーカイブログの保護ポリシーに基づいてアーカイブログファイルを保護するように指定します。

+
-noftect オプションを使用して、アーカイブログファイルを保護しないように指定します。

* *-include-y-one-backups|-no-include-online-backups*
+
オンラインデータベースバックアップにアーカイブログバックアップを含めるように指定します。

+
オンラインデータベースバックアップにアーカイブログバックアップを含めないように指定します。

* * -dump*
+
プロファイル作成処理が成功したあとにダンプ・ファイルを収集するように指定します。

* * - Quiet *
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* * -verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。





== 例

次に、プロファイルで説明されているデータベースのログイン情報を変更し、このプロファイルに電子メール通知を設定する例を示します。

[listing]
----
smo profile update -profile SALES1 -database -dbname SALESDB
 -sid SALESDB -login -username admin2 -password d4jPe7bw -port 1521
-host server1 -profile-notification -success -e-mail Preston.Davis@org.com -subject success
Operation Id [8abc01ec0e78ec33010e78ec3b410001] succeeded.
----
* 関連情報 *

xref:task_changing_profile_passwords.adoc[プロファイルのパスワードを変更する]

xref:concept_how_snapmanager_retains_backups_on_the_local_storage.adoc[SnapManager がローカルストレージ上にバックアップを保持する方法]
