---
permalink: unix-administration/reference_troubleshooting_snapmanager.html 
sidebar: sidebar 
keywords: information, common, issue, resolve, troubleshoot, snapmanager 
summary: ここでは、発生する可能性のある最も一般的な問題とその解決方法について説明します。 
---
= SnapManager のトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ここでは、発生する可能性のある最も一般的な問題とその解決方法について説明します。

次の表に、一般的な問題と解決策を示します。

|===
| 問題主導の質問 | 解決策の可能性があります 


 a| 
ターゲット・データベースとリスナーは動作していますか
 a| 
lsnrctl status コマンドを実行します。データベース・インスタンスがリスナーに登録されていることを確認します。



 a| 
ストレージは認識されていますか。
 a| 
SnapDrive storage show -all コマンドを実行します。



 a| 
ストレージは書き込み可能ですか。
 a| 
作成したマウントポイント内のファイルを編集します。タッチファイル名コマンドを使用します。ファイルが作成されると、ストレージは書き込み可能になります。SnapManager を実行するユーザがストレージに書き込めることを確認します（ UNIX の root など）。



 a| 
SnapManager サーバは稼働していますか。
 a| 
smo _server start コマンドを使用して、サーバの起動を試行します。

グラフィカルユーザインターフェイス（ GUI ）またはコマンドラインインターフェイス（ CLI ）を使用してプロファイルに関連する SnapManager コマンドを開始するには、サーバが稼働している必要があります。サーバを起動せずにリポジトリを作成または更新できますが、他のすべての SnapManager 操作を実行するには、サーバが実行されている必要があります。

SnapManager サーバを起動するには、次のコマンドを入力します。 smo _server start



 a| 
SnapManager の実行に必要なすべてのコンポーネントが正しく設定されていますか？
 a| 
smo system verify コマンドを実行して、 SnapDrive が正しく設定されていることを確認します。



 a| 
正しいバージョンの SnapManager を使用していますか？
 a| 
smo version コマンドを使用して、 SnapManager のバージョンを確認します。



 a| 
問題ログファイルを調べて、エラーメッセージが SnapManager の特定に役立つかどうかを確認しましたか。
 a| 
SnapManager は、すべてのログ・エントリを 1 組の循環型ログ・ファイルに記録します。ログファイルは /var/log/smo にあります。

ログファイルは C ： \Program Files\NetApp\SnapManager for Oracle\logs にあります。

次の場所のログを確認すると便利な場合があります。

/usr/home/ 。 NetApp / smo /3.3.0 /log/

各処理ログは、 smo _OF_date_time.log 形式の固有のログ・ファイルに書き込まれます。



 a| 
Data ONTAP を実行していないストレージ・システムにアーカイブ・ログが格納されている場合、 SnapManager でのバックアップ処理からそれらのログを除外しましたか。
 a| 
smo .config ファイルを使用すると、特定のアーカイブ・ログ・ファイルを除外することができます。UNIX の場合、ファイルは /opt/netapp/smo/properties/smo.config の場所にあります

ローカルアーカイブログを除外するには、ファイルに記載されている形式を使用します。追加情報については、「設定プロパティ」のトピックを参照してください。

SnapManager CLI からバックアップを作成する際に、アーカイブログのデスティネーションを除外することもできます。追加情報については ' データベース・バックアップの作成に関するトピックを参照してください

SnapManager の GUI からバックアップを作成する際に、アーカイブログのデスティネーションを除外することもできます。



 a| 
SnapManager と NFS データベースを併用する場合は、 FlexClone ライセンスがありますか？
 a| 
SnapManager を NFS データベースで最大限に活用するには、 FlexClone ライセンスが必要です。SnapManager は、 FlexClone 機能を使用して次の処理を実行します。

* NFS データベースのバックアップのマウント
* NFS データベースのバックアップの検証
* NFS データベースのクローニング
* NFS データベースのバックアップの RMAN への登録（ RMAN を使用している場合）




 a| 
リポジトリに接続できませんでしたか ?
 a| 
リポジトリへの接続に失敗した場合は、リポジトリデータベースで lsnrctl status コマンドを実行して、アクティブなサービス名を確認します。SnapManager がリポジトリデータベースに接続すると、データベースのサービス名が使用されます。リスナーの設定によっては、短縮サービス名または完全修飾サービス名が使用されます。バックアップ、リストア、またはその他の処理のために SnapManager がデータベースに接続するときは、ホスト名と SID が使用されます。リポジトリが現在アクセスできないために正常に初期化されない場合は ' リポジトリを削除するかどうかを確認するエラー・メッセージが表示されますリポジトリを現在のビューから削除すると、他のリポジトリに対しても処理を実行できます。

また 'PS-eaf を実行して ' リポジトリ・インスタンスが実行されているかどうかを確認します



| grepinstance-name コマンド  a| 
ホスト名はシステムで解決できるか。



 a| 
指定したホスト名が別のサブネット上にあるかどうかを確認してください。SnapManager でホスト名を解決できないというエラーメッセージが表示された場合は、ホストファイルにホスト名を追加します。 /etc/hosts ： xxx.xxx.xxx.xxx hostname IP address にあるファイルにホスト名を追加します
 a| 
SnapDrive は稼働していますか。



 a| 
SnapDrive デーモンが実行されているかどうかを確認します。 -snapdrived status

デーモンが実行されていない場合は、接続エラーが発生したことを示すメッセージが表示されます。
 a| 
SnapDrive でアクセスするように設定されているストレージシステムはどれですか？



 a| 
SnapDrive 設定リストコマンドを実行します
 a| 
SnapManager GUI のパフォーマンスはどのように向上するのですか。



 a| 
* リポジトリ、プロファイルホスト、およびプロファイルの有効なユーザ・クレデンシャルがあることを確認します。
+
クレデンシャルが無効な場合は、リポジトリ、プロファイルホスト、およびプロファイルのユーザクレデンシャルを消去してください。リポジトリ、プロファイルホスト、およびプロファイルに対して以前に設定したユーザクレデンシャルをリセットします。追加情報のユーザクレデンシャルの再設定については、「クレデンシャルキャッシュをクリアした後のクレデンシャルの設定」を参照してください。

* 未使用のプロファイルを閉じます。
+
開いているプロファイルの数が多い場合、 SnapManager の GUI のパフォーマンスは低下します。

* SnapManager GUI から、「ユーザー環境設定」ウィンドウの「管理者」メニューで「起動時に開く」が有効になっているかどうかを確認します。
+
このオプションを有効にすると、 /root/.NetApp/smo /3.3.3.0 /guo/state にあるユーザ設定（ user.config ）ファイルが openOnStartup=profile と表示されます。

+
* 起動時に開く * が有効になっているため、ユーザー設定（ user.config ）ファイルで lastOpenProfiles を使用して、 SnapManager GUI から最近開かれたプロファイルを確認する必要があります。 lastOpenProfiles = Profile1 、 profile2 、 PROFILE3 など。

+
リストされているプロファイル名を削除して、開いているプロファイルの数を常に最小限に抑えることができます。

* 保護されたプロファイルは、保護されていないプロファイルよりも更新に時間がかかります。
+
保護されたプロファイルは、ユーザ設定（ user.config ）ファイルの protectionStatusRefreshRate パラメータで指定された値に基づいて、一定の時間間隔で更新されます。

+
デフォルト値（ 300 秒）から値を大きくすると、指定した間隔で保護プロファイルが更新されないようにすることができます。

* UNIX ベースの環境に SnapManager の新しいバージョンをインストールする前に、次の場所にある SnapManager クライアント側のエントリを削除します。
+
/root/. netapp


 a| 
複数の SnapManager 処理がバックグラウンドで同時に開始されて実行されている場合、 SnapManager GUI の更新に時間がかかります。バックアップを右クリックすると（すでに削除されているが SnapManager GUI に表示される）、そのバックアップのバックアップ・オプションは [Backup or Clone] ウィンドウでは有効になりません。



 a| 
SnapManager の GUI が更新されるまで待ってから、バックアップのステータスを確認する必要があります。
 a| 
Oracle データベースが英語で設定されていない場合はどうすればよいですか。



 a| 
Oracle データベースの言語が英語に設定されていないと、 SnapManager の処理が失敗することがあります。Oracle データベースの言語を英語に設定します。

. /etc/init.d/smo _server の初期コメントに次の項目を追加します
+
** NLS_LANG = America_America
** NLS_LANG をエクスポートします


. 次のコマンドを使用して、 SnapManager サーバを再起動します。 smo _server restart



NOTE: Oracle ユーザーの .bash_profile 、 .bashrc 、 .cshrc などのログインスクリプトが NLS_LANG に設定されている場合は、 NLS_LANG を上書きしないようにスクリプトを編集する必要があります。
 a| 
リポジトリ・データベースが複数の IP を指していて、各 IP のホスト名が異なる場合に、バックアップのスケジュール設定処理が失敗するとどうなりますか。



 a| 
. SnapManager サーバを停止します。
. リポジトリディレクトリ内のスケジュールファイルは、バックアップスケジュールをトリガーするホストから削除します。
+
スケジュールファイル名は次の形式にすることができます。

+
** リポジトリ #repo_username#repository_database_name #repository_host#repo_port
** repository -repo_namerestory_database_name -repository_host-repo_port * 注： * リポジトリの詳細に一致する形式でスケジュールファイルを削除する必要があります。


. SnapManager サーバを再起動します。
. SnapManager GUI から同じリポジトリの下にある他のプロファイルを開き、これらのプロファイルのスケジュール情報が失われないようにします。

 a| 
クレデンシャルファイルロックエラーが発生して SnapManager 処理が失敗した場合、どうすればよいですか？



 a| 
SnapManager は、更新前にクレデンシャルファイルをロックし、更新後にロックを解除します。複数の処理を同時に実行すると、いずれかの処理によって、クレデンシャルファイルがロックされて更新されることがあります。ロックされたクレデンシャルファイルに同時に別の処理でアクセスしようとすると、ファイルロックエラーが発生して処理が失敗します。

smo .config ファイルでは、同時に実行する処理の頻度に応じて次のパラメータを設定します。

* FileLock.RetryInterval=100 ミリ秒
* FileLock.timeout=5000 ミリ秒



NOTE: パラメータには、ミリ秒単位の値を指定する必要があります。
 a| 
バックアップ検証処理がまだ実行中であっても、バックアップ検証処理の中間ステータスが Monitor タブに failed と表示された場合はどうすればよいですか？



 a| 
エラーメッセージは sm_gui.log ファイルに記録されます。ログファイルを参照して、操作の新しい値を確認する必要があります。 heartbeatInterval および操作。 heartbeatThreshold パラメータは、この問題を解決します。

. smo .config ファイルに次のパラメータを追加します。
+
** operation.heartbeatInterval=5000
** operation.heartbeatThreshold =5000 SnapManager によって割り当てられたデフォルト値は 5000 です。


. これらのパラメータに新しい値を割り当てます。
+

NOTE: パラメータには、ミリ秒単位の値を指定する必要があります。

. SnapManager サーバを再起動し、処理を再実行してください。

 a| 
ヒープ領域の問題が発生した場合の対処方法



 a| 
SnapManager for Oracle の処理中にヒープスペース問題が発生した場合は、次の手順を実行する必要があります。

. SnapManager for Oracle のインストールディレクトリに移動します。
. installationdirectory/bin/launchjava パスから launchjava ファイルを開きます。
. java -Xmx160m java heap-space パラメータの値を大きくします。
+
たとえば、デフォルト値の 160m を 200 m に増やすことができます。

+

NOTE: 以前のバージョンの SnapManager for Oracle で Java heap-space パラメータの値を増やした場合は、この値を維持する必要があります。


 a| 
保護されたバックアップを使用してリストアまたはクローンを作成できない場合はどうすればよいですか？



 a| 
この問題は、 clustered Data ONTAP に SnapManager 3.3.1 を使用していて、 SnapManager 3.4 にアップグレードしている場合に確認されます。バックアップは、 SnapManager 3.3.1 のポストスクリプトを使用して保護されています。SnapManager 3.4 からは、プロファイルの作成時に選択した _SnapManager_cDOT _ Mirror _ または _SnapManager_cDOT _ Vault _ ポリシーを使用してバックアップが保護されます。 SnapManager 3.4 へのアップグレード後も古いプロファイルを使用しているため、バックアップはバックアップスクリプトを使用して保護されます。 ただし、 SnapManager を使用したリストアやクローニングでは使用できません。

プロファイルを更新して、 _SnapManager_cDOT _ ミラー _ または _SnapManager_cDOT _ ボールト _ ポリシーを選択し、 SnapManager 3.3 でデータ保護に使用したポストスクリプトを削除する必要があります。
 a| 
スケジュールされたバックアップが保護されていない場合（ SnapVault ）はどうすればよいですか。

|===