---
permalink: unix-administration/reference_the_smosmsapbackup_create_command.html 
sidebar: sidebar 
keywords: run, backup, create, command, database, storage, system, smo 
summary: backup create コマンドを実行すると、 1 つ以上のストレージシステム上にデータベースバックアップを作成できます。 
---
= smo backup create コマンド
:icons: font
:imagesdir: ../media/


[role="lead"]
backup create コマンドを実行すると、 1 つ以上のストレージシステム上にデータベースバックアップを作成できます。



== 構文


NOTE: このコマンドを実行する前に、 profile create コマンドを使用してデータベースプロファイルを作成する必要があります。

[listing]
----

        smo backup create
-profile profile_name
{\[-full\{-auto \| -online \| -offline\}\[-retain \{-hourly \| -daily \| -weekly \| -monthly \| -unlimited\} \[-verify\]  |
\[-data \[\[-files files \[files\]\] \|
\[-tablespaces tablespaces \[tablespaces\]\] \[-label label\] \{-auto \| -online \| -offline\}
\[-retain \{-hourly \| -daily \| -weekly \| -monthly \| -unlimited\} \[-verify\] |
\[-archivelogs \[-label label\]\] \[-comment comment\]}
\[-protect \| -noprotect \| -protectnow\]
\[-backup-dest path1 \[ , path2\]\]
\[-exclude-dest path1 \[ , path2\]\]
\[-prunelogs \{-all \| -until-scn until-scn \| -until-date yyyy-MM-dd:HH:mm:ss\] \| -before \{-months \| -days \| -weeks \| -hours}}
-prune-dest prune_dest1,\[prune_dest2\]\]
\[-taskspec taskspec\]
\[-dump\]
-force
\[-quiet \| -verbose\]
----


== パラメータ

* * -profile profile_name *
+
バックアップするデータベースに関連するプロファイルの名前を指定します。プロファイルには、データベースの識別子およびその他のデータベース情報が含まれています。

* * - auto オプション *
+
データベースがマウント済み状態またはオフライン状態の場合、 SnapManager はオフラインバックアップを実行します。データベースが OPEN または ONLINE 状態の場合、 SnapManager はオンライン・バックアップを実行します。force オプションを -offline オプションと指定すると、データベースが現在オンラインである場合でも、 SnapManager によってオフライン・バックアップが強制的に実行されます。

* * - オンラインオプション *
+
オンライン・データベース・バックアップを指定します。

+
Real Application Clusters （ RAC ）データベースのオンラインバックアップは、プライマリがオープン状態である場合、またはプライマリがマウントされていてインスタンスがオープン状態である場合にかぎり作成できます。ローカルインスタンスがシャットダウン状態にある場合、またはどのインスタンスも OPEN 状態にない場合に、オンライン・バックアップに -force オプションを使用できます。Oracle のバージョンは 10.2.0.5 である必要があります。そうでない場合、 RAC 内のいずれかのインスタンスがマウントされると、データベースは停止します。

+
** ローカルインスタンスがシャットダウン状態で、少なくとも 1 つのインスタンスがオープン状態の場合は、 -force オプションを使用して、ローカルインスタンスを MOUNTED 状態に変更できます。
** オープン状態のインスタンスがない場合は、 -force オプションを使用して、ローカルインスタンスをオープン状態に変更できます。


* * -offline オプション *
+
データベースがシャットダウン状態のときに、オフラインバックアップを実行するように指定します。データベースが OPEN または MOUNTED の場合には、バックアップは失敗します。force オプションを使用した場合、 SnapManager はデータベースの状態を変更し、オフライン・バックアップのためにデータベースをシャットダウンしようとします。

* * - フルオプション *
+
データベース全体がバックアップされます。これには、すべてのデータ、アーカイブログ、および制御ファイルが含まれます。アーカイブ REDO ログおよび制御ファイルは、実行するバックアップのタイプに関係なくバックアップされます。データベースの一部だけをバックアップする場合は、 -files オプションまたは -tablespaces オプションを使用します。

* * -data* オプション *
+
データファイルを指定します。

* * - ファイルリスト *
+
指定されたデータファイル、およびアーカイブされたログファイルと制御ファイルのみをバックアップします。ファイル名のリストはスペースで区切ります。データベースが OPEN 状態の場合、 SnapManager は該当する表領域がオンライン・バックアップ・モードになっているかどうかを確認します。

* * - 表領域 *
+
指定されたデータベースの表領域、およびアーカイブされたログファイルと制御ファイルのみをバックアップします。表領域名はスペースで区切ります。データベースが OPEN 状態の場合、 SnapManager は該当する表領域がオンライン・バックアップ・モードになっているかどうかを確認します。

* * - ラベルラベル *
+
このバックアップのオプション名を指定します。この名前はプロファイル内で一意である必要があります。名前には、アルファベット、数字、アンダースコア（ _ ）、およびハイフン（ - ）を使用できます。1 文字目をハイフンにすることはできません。ラベルを指定しない場合、 SnapManager は scope_type_date 形式でデフォルトのラベルを作成します。

+
** 範囲は F でフル・バックアップを示し 'P ではパーシャル・バックアップを示します
** type は、オフライン（コールド）バックアップを示す C 、オンライン（ホット）バックアップを示す H 、または自動バックアップを示す A です（例： P_A_20081010060037IST ）。
** date は、バックアップを作成した年月日、および時刻です。
+
SnapManager は 24 時間方式のクロックを使用します。



+
たとえば、 2007 年 1 月 16 日の午後 5 時 45 分 16 分にデータベースをオフラインにしてフルバックアップを実行したとします東部標準時、 SnapManager はラベル F_C_20070116174516EST を作成します。

* * -comment string*
+
このバックアップに関するコメントを指定します。文字列は一重引用符（ ' ）で囲みます。

+

NOTE: 一部のシェルでは、引用符が除去されます。この場合は、引用符にバックスラッシュ（ \ ）を含める必要があります。たとえば、次のように入力する必要があります。「 \ 」これはコメントです。

* * -verify オプション *
+
Oracle の dbv ユーティリティを実行して、バックアップ内のファイルが破損していないかどうかが検証されます。

+

NOTE: verify オプションを指定した場合、検証処理が完了するまで、バックアップ処理は完了しません。

* * -force オプション *
+
データベースが正しい状態でない場合に、状態を強制的に変更します。たとえば、指定したバックアップのタイプおよびデータベースの状態に基づいて、 SnapManager によってデータベースの状態がオンラインからオフラインに変更されることがあります。

+
RAC データベースをオンラインでバックアップする場合は、ローカルインスタンスがシャットダウン状態にあるか、インスタンスが OPEN 状態になっていないときに、 -force オプションを使用します。

+

NOTE: Oracle のバージョンは 10.2.0.5 である必要があります。そうでない場合、 RAC 内のいずれかのインスタンスがマウントされると、データベースは停止します。

+
** ローカルインスタンスがシャットダウン状態で、少なくとも 1 つのインスタンスが OPEN 状態の場合に、 -force オプションを使用すると、ローカルインスタンスが MOUNTED 状態に変更されます。
** OPEN 状態のインスタンスがない場合に、 -force オプションを使用すると、ローカル・インスタンスが OPEN 状態に変更されます。


* * - Quiet *
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* * -verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。

* *-protect | -nobprotect | -protectnow *
+
バックアップをセカンダリストレージで保護するかどうかを指定します。noprotect オプションは、バックアップをセカンダリ・ストレージで保護しないように指定します。フルバックアップのみが保護されます。どちらのオプションも指定しない場合、バックアップがフルバックアップで、プロファイルで保護ポリシーが指定されていれば、 SnapManager はバックアップをデフォルトとして保護します。protectnow オプションは、 Data ONTAP 7-Mode でのみ使用できます。オプションは、バックアップをセカンダリストレージですぐに保護するように指定します。

* * - ｛ -hourly | -daily | -weekly | -monthly | -unlimited ｝ * を保持できます
+
バックアップを時間単位、日単位、週単位、月単位、または無制限単位で保持するかどうかを指定します。retain オプションが指定されていない場合 ' 保存クラスはデフォルトで -hourly オプションに設定されますバックアップを無期限に保持するには、 -unlimited オプションを使用します。unlimited オプションを指定すると、バックアップは保持ポリシーで削除できなくなります。

* *-archivelogs オプション *
+
アーカイブログバックアップを作成します。

* *-backup-dest path1 、 [,[path2]*
+
アーカイブログバックアップ用にバックアップするアーカイブログのデスティネーションを指定します。

* *-exclude-dest path1,[,[path2]*
+
バックアップから除外するアーカイブログの送信先を指定します。

* *-prunelogs {-all|-until -scnuntil -scnuntil -dateyyyy-md-dd ： HH ： mm ： ss | -before ｛ -months | -days | -weeks | -hours ｝ *
+
バックアップの作成時に指定したオプションに基づいて、アーカイブログデスティネーションからアーカイブログファイルを削除します。all オプションを指定すると、アーカイブログのデスティネーションからすべてのアーカイブログファイルが削除されます。until SCN オプションを使用すると、指定した System Change Number （ SCN ）までアーカイブログファイルが削除されます。until date オプションを使用すると、指定した期間が経過するまでアーカイブ・ログ・ファイルが削除されます。before オプションを指定すると、指定した期間（日、月、週、時間）前のアーカイブログファイルが削除されます。

* *-prune-dest prune_dest1 、 prune_dest2 *
+
バックアップの作成時に、アーカイブログデスティネーションからアーカイブログファイルを削除します。

* *-taskspec taskspec *
+
バックアップ処理の前処理アクティビティまたは後処理アクティビティに使用できるタスク仕様 XML ファイルを指定します。taskspec オプションを指定するときに、 XML ファイルの完全なパスを指定する必要があります。

* * -dump オプション *
+
データベースバックアップ処理が成功したか失敗したあとにダンプファイルを収集します。





== コマンドの例

次のコマンドでは、フルオンラインバックアップを作成し、セカンダリストレージにバックアップを作成して、保持ポリシーを daily に設定します。

[listing]
----
smo backup create -profile SALES1 -full -online
-label full_backup_sales_May -profile SALESDB -force -retain -daily
Operation Id [8abc01ec0e79356d010e793581f70001] succeeded.
----
* 関連情報 *

xref:task_creating_database_backups.adoc[データベースバックアップを作成しています]

xref:reference_the_smosmsapprofile_create_command.adoc[smo profile create コマンド]

xref:concept_restoring_protected_backups_from_secondary_storage.adoc[セカンダリストレージから保護されたバックアップをリストアする]
