---
permalink: unix-administration/reference_the_smosmsaprepository_create_command.html 
sidebar: sidebar 
keywords: smo, repository, creat, command 
summary: このコマンドは、データベースプロファイルおよび関連付けられたクレデンシャルを格納するリポジトリを作成します。 
---
= smo repository create コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== 構文

このコマンドは、データベースプロファイルおよび関連付けられたクレデンシャルを格納するリポジトリを作成します。また、このコマンドはブロックサイズが適切かどうかもチェックします。

[listing]
----

        smo repository create
-repository
-port repo_port
-dbname repo_service_name
-host repo_host
-login -username repo_username
[-force] [-noprompt]
\[-quiet \| -verbose\]
----


== パラメータ

* * - リポジトリ *
+
repository のあとに続くオプションは、リポジトリに対応するデータベースの詳細を指定します

* * -port repo_port *
+
リポジトリが格納されたデータベースへのアクセスに使用する TCP ポート番号を指定します。

* * -dbname repo_service_name *
+
リポジトリが格納されたデータベースの名前を指定します。グローバル名または SID を使用します。

* * -host repo_host *
+
リポジトリ・データベースが稼働しているホスト・コンピュータの名前または IP アドレスを指定します。

* * - ログイン *
+
リポジトリ・ログインの詳細設定を開始します。

* * -username repo_username *
+
リポジトリが格納されたデータベースにアクセスするために必要なユーザ名を指定します。

* * -force *
+
リポジトリを強制的に作成しようとします。このオプションを使用すると、 SnapManager により、リポジトリを作成する前にリポジトリのバックアップを促すプロンプトが表示されます。

* * -noprompt *
+
force オプションを使用した場合、は、リポジトリを作成する前にリポジトリのバックアップを促すプロンプトを表示しません。noprompt オプションを使用するとプロンプトが表示されないため、スクリプトを使用したリポジトリの作成が容易になります。

* * - Quiet *
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* * -verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。





== コマンド例

次の例では、ホスト Hotspur 上のデータベース SMOREPO にリポジトリを作成します。

[listing]
----
smo repository create -repository -port 1521 -dbname SMOREPO -host hotspur -login -username grabal21 -verbose
SMO-09202 [INFO ]: Creating new schema as grabal21 on jdbc:oracle:thin:@//hotspur:1521/SMOREPO.
SMO-09205 [INFO ]: Schema generation complete.
SMO-09209 [INFO ]: Performing repository version INSERT.
SMO-09210 [INFO ]: Repository created with version: 30
SMO-13037 [INFO ]: Successfully completed operation: Repository Create
SMO-13049 [INFO ]: Elapsed Time: 0:00:08.844
----