---
permalink: unix-administration/reference_the_smosmsapbackup_restore_command.html 
sidebar: sidebar 
keywords: run, backup, restore, command, database, portion, optional, smo, information 
summary: backup restore コマンドを実行してデータベースまたはデータベースの一部のバックアップをリストアし、必要に応じてデータベース情報をリカバリすることができます。 
---
= smo backup restore コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
backup restore コマンドを実行してデータベースまたはデータベースの一部のバックアップをリストアし、必要に応じてデータベース情報をリカバリすることができます。



== 構文

[listing]
----

        smo backup restore
-profile profile_name
\[-label label \| -id id\]
\[-files files \[files...\] \|
-tablespaces tablespaces \[tablespaces...\]\] \|
-complete \| -controlfiles\]
\[-recover \{-alllogs \| -nologs \| -until until\} \[-using-backup-controlfile\] \]
\[-restorespec restorespec \| -from-secondary \[-temp-volume temp_volume\] \[-copy-id id\]\]
\[-preview\]
\[-fast \{-require \| -override \| -fallback \| -off\}\]
\[-recover-from-location path1 \[, path2\]\]
\[-taskspec taskspec\]
\[-dump\]
\[-force\]
\[-quiet \| -verbose\]
----


== パラメータ

* * -profile profile_name *
+
リストアするデータベースを指定します。プロファイルには、データベースの識別子およびその他のデータベース情報が含まれています。

* * - ラベル名 *
+
指定したラベルを持つバックアップをリストアします。

* *-id GUID*
+
指定した GUID を持つバックアップをリストアします。GUID はバックアップを作成するときに SnapManager によって生成されます。各バックアップの GUID を表示する場合は、 smo backup list コマンドを使用します。

* * すべてのファイルまたは指定されたファイルを選択 *
+
必要に応じて、次のいずれかのオプションを使用できます。

+
** -complete ：バックアップ内のすべてのデータ・ファイルをリストアします。
** -tablespaceslist ：指定した表領域のみをバックアップからリストアします。
+
リスト内で名前を区切るには、スペースを使用する必要があります。

** -fileslist ：指定したデータ・ファイルだけをバックアップからリストアします。
+
リスト内で名前を区切るには、スペースを使用する必要があります。データベースが稼働している場合、 SnapManager はファイルを含む表領域がオフラインであることを確認します。



* *-controlfiles *
+
制御ファイルをリストアします。SnapManager では、バックアップ内のデータ・ファイルと制御ファイルを一度にリストアできます。controlfiles オプションは、 -complete 、 -tablespaces 、 -files などのリストア範囲パラメータから独立しています。

* *-recover*
+
リストア後にデータベースをリカバリします。また、次のいずれかのオプションを使用して、 SnapManager でデータベースのリカバリ・ポイントを指定する必要があります。

+
** -nologs ：バックアップ時点までデータベースをリカバリし、ログを適用しない
+
このパラメータは、オンラインバックアップまたはオフラインバックアップに使用できます。

** -alllogs ：データベースを最後のトランザクションまたはコミットまでリカバリし、必要なすべてのログを適用します。
** - 終了日：指定された日時までデータベースをリカバリします。
+
年 - 月 - 日：時：分：秒（ yyyy-mm-dd ： hh ： mm ： ss ）の形式を使用する必要があります。データベースの設定に応じて、 12 時間形式または 24 時間形式のどちらかを使用してください。

** -until scn ：指定したシステム変更番号（ SCN ）に達するまで、データファイルをロールフォワードします。
** -use-backup-controlfile ：バックアップ制御ファイルを使用してデータベースをリカバリします。


* * -restorespec *
+
元の各 Snapshot コピーがアクティブファイルシステムにマッピングされているため、データをアクティブファイルシステムにリストアし、指定したデータからリストアすることができます。オプションを指定しない場合、 SnapManager はプライマリストレージ上の Snapshot コピーからデータをリストアします。次のいずれかのオプションを指定できます。

+
** -restorespec ：リストアするデータおよびリストア形式を指定します。
** セカンダリから：セカンダリストレージからデータをリストアします。
+
プライマリストレージにバックアップが存在する場合は、このオプションを使用できません。セカンダリストレージからバックアップをリストアするには、プライマリバックアップを解放しておく必要があります。一時ボリュームを使用する場合は、 -temp-volume オプションを使用してボリュームを指定する必要があります。

+
from-secondary オプションを指定した場合は、必ず -copy-id オプションを指定する必要があります。セカンダリストレージシステムに複数のバックアップがある場合は、 -copy-id オプションを使用して、リストア処理に使用するセカンダリストレージ上のバックアップコピーを指定します。

+

NOTE: Data ONTAP 7-Mode を使用している場合は、 -copy-id オプションに有効な値を指定する必要があります。ただし、 clustered Data ONTAP を使用している場合は、 -copy-id オプションは不要です

+
SnapManager は、セカンダリストレージからリストアする際、最初に（ホストを介さずに）セカンダリストレージシステムからプライマリストレージシステムにデータを直接リストアします。SnapManager がこのタイプのリストアを実行できない場合（ファイルがファイルシステムの一部でない場合など）、 SnapManager はホスト側のファイルコピーのリストアにフォールバックします。SnapManager では、セカンダリからホスト側のファイルコピーのリストアを 2 つの方法で実行できます。SnapManager で選択される方法は、 smo .config ファイルに設定されています。

** 直接： SnapManager はセカンダリストレージ上にデータのクローンを作成し、クローニングされたデータをセカンダリストレージシステムからホストにマウントして、クローンのデータをアクティブ環境にコピーします。
+
これはデフォルトのセカンダリアクセスポリシーです。

** 間接： SnapManager は、最初にプライマリストレージ上の一時ボリュームにデータをコピーし、一時ボリュームからホストにデータをマウントしてから、一時ボリュームからアクティブな環境にデータをコピーします。
+
このポリシーは、ホストがセカンダリストレージシステムに直接アクセスできない場合にのみ使用してください。間接方式を使用したリストアでは、データのコピーが 2 つ作成されるため、セカンダリへの直接アクセスポリシーに 2 倍の時間がかかります。



+
直接方式と間接方式のどちらを使用するかは、 smo .config 構成ファイルの restore.secondaryAccessPolicy パラメータの値によって決まります。

* * - プレビュー *
+
次の情報を表示します。

+
** 各ファイルのリストアに使用するリストアメカニズム（高速リストア、ストレージ側のファイルシステムのリストア、ストレージ側のファイルのリストア、またはホスト側のファイルコピーのリストア
** 各ファイルのリストアに、より効率的なメカニズムが使用されていない理由。 -preview オプションを使用している場合は -verbose オプションを指定すると、次の点を確認する必要があります。
** force オプションは、コマンドには影響しません。
** recover オプションは ' コマンドには影響しません
** fast オプション（ -require 、 -override 、 -fallback 、または -off ）は、出力に大きな影響を与えます。リストア処理をプレビューするには、データベースをマウントする必要があります。リストア計画をプレビューする際に、データベースが現在マウントされていない場合は、 SnapManager によってデータベースがマウントされます。データベースをマウントできない場合、コマンドは失敗し、 SnapManager はデータベースを元の状態に戻します。


+
preview オプションを指定すると、最大 20 個のファイルが表示されます。smo .config ファイルに表示するファイルの最大数を設定することができます。

* * -fe*
+
リストア処理で使用するプロセスを選択できます。必須のリストア条件がすべて満たされている場合は、 SnapManager で他のリストアプロセスではなくボリュームベースの高速リストアプロセスを強制的に使用できます。ボリュームリストアを実行できないことがわかっている場合は、このプロセスを使用して、高速リストアプロセスを使用して、 SnapManager で適格性チェックとリストア処理を実行できないようにすることもできます。

+
fast オプションには、次のパラメータが含まれています。

+
** -require ：すべてのリストア条件が満たされている場合に、 SnapManager でボリュームのリストアを強制的に実行できます。
+
fast オプションを指定した場合、 -fast パラメータを指定しないと、 SnapManager では -require パラメータをデフォルトとして使用します。

** -override ：必須でない適格性チェックを無視し、ボリュームベースの高速リストアプロセスを実行できます。
** -fallback ： SnapManager で判断された方法を使用してデータベースをリストアできます。
+
fast オプションを指定しない場合、 SnapManager ではデフォルトのバックアップリストア高速フォールバックオプションが使用されます。

** -off ：資格チェックの実行にかかる時間を短縮できます。


* * -recovery-from-location*
+
アーカイブログファイルの外部アーカイブログの場所を指定します。SnapManager は外部の場所からアーカイブログファイルを取得し、リカバリプロセスに使用します。

* *-taskspec*
+
リストア処理の前処理アクティビティまたは後処理アクティビティのタスク仕様 XML ファイルを指定します。タスク仕様 XML ファイルの完全なパスを指定する必要があります。

* * -dump*
+
リストア処理後にダンプファイルを収集するように指定します。

* * -force *
+
必要に応じて、データベースの状態を現在の状態よりも低い状態に変更します。Real Application Clusters （ RAC ）の場合、 SnapManager で RAC インスタンスの状態を低いレベルに変更する必要があるときは、 -force オプションを指定する必要があります。

+
デフォルトでは、 SnapManager は処理中にデータベースを高いレベルの状態に変更できます。SnapManager でデータベースを高いレベルの状態に変更する場合、このオプションは必要ありません。

* * - Quiet *
+
コンソールにエラーメッセージのみを表示します。デフォルト設定では、エラーおよび警告メッセージが表示されます。

* * -verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。このオプションを使用すると、より効率的なリストアプロセスでファイルをリストアできなかった理由を確認できます。





== 例

次に、データベースおよび制御ファイルをリストアする例を示します。

[listing]
----
smo backup restore -profile SALES1 -label full_backup_sales_May
-complete -controlfiles -force
----
* 関連情報 *

xref:concept_restoring_database_backup.adoc[データベースバックアップのリストア]

xref:task_restoring_backups_from_an_alternate_location.adoc[別の場所からのバックアップのリストア]

xref:task_creating_restore_specifications.adoc[リストア仕様を作成しています]
