---
permalink: unix-administration/reference_the_smosmsap_notification_updatesummarynotification_command.html 
sidebar: sidebar 
keywords: run, notification, update-summary-notification, command, summary, enable, repository, database, smo 
summary: notification update-summary-notification コマンドを実行すると、リポジトリデータベースのサマリー通知をイネーブルにできます。 
---
= smo notification update-summary-notification コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
notification update-summary-notification コマンドを実行すると、リポジトリデータベースのサマリー通知をイネーブルにできます。



== 構文

[listing]
----

        smo notification update-summary-notification
-repository
-port repo_port
-dbname  repo_service_name
-host repo_host
-login -username repo_username
-email email-address1,email-address2
-subject subject-pattern
-frequency
[-daily –time daily_time \|
-hourly –time hourly_time \|
-monthly –time monthly_time -date \[1\|2\|3\|...\|31\] \|
-weekly  –time weekly_time -day \[1\|2\|3\|4\|5\|6\|7\]\]
-profiles profile1,profile2
-notification-host notification-host
\[-quiet \| -verbose\]
----


== パラメータ

* * - リポジトリ *
+
リポジトリ・データベースの詳細を指定します。

* * -port repo_port *
+
リポジトリ・データベースへのアクセスに使用する TCP ポート番号を指定します。

* * -dbname repo_service_name *
+
リポジトリ・データベースの名前を指定します。グローバル名またはシステム ID を使用できます。

* * -host repo_host *
+
リポジトリ・データベースが格納されているホストの名前または IP アドレスを指定します。

* * - ログイン *
+
リポジトリ・ログインの詳細を指定します。これはオプションです。指定しない場合、 SnapManager はデフォルトで OS 認証接続モードになります。

* * -username repo_username *
+
リポジトリ・データベースへのアクセスに必要なユーザ名を指定します。

* *- 電子メールアドレス 1 、電子メールアドレス 2 *
+
受信者の E メールアドレスを指定します。

* * -subject subject-pattern *
+
E メールの件名のパターンを指定します。

* * -frequency ｛ -daily --time daily_time | -hourly --time hourly_schedule_time | -monthly --time monthly_schedule-date ｛ 1 | 2 | 3 ... | 31 ｝ | -weekly -- time weekly_time -day ｛ 1 | 2 | 3 | 4 | 5 | 6 | 7 ｝ *
+
E メール通知を使用するスケジュールのタイプとスケジュールの時刻を指定します。

* * -profiles profile1 、 profile2 *
+
E メール通知を必要とするプロファイル名を指定します。

* *-notification-host notification-host*
+
サマリー通知 E メールの送信元である SnapManager サーバホストを指定します。通知ホストのホスト名または IP アドレスを指定できます。ホストの IP 名またはホスト名を更新することもできます。

* * - Quiet *
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* * -verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。





== 例

次に、リポジトリデータベースのサマリー通知をイネーブルにする例を示します。

[listing]
----

smo notification update-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login –username oba5 –email admin@org.com –subject success –frequency -daily -time 19:30:45 –profiles sales1
----