---
permalink: unix-administration/reference_the_smosmsapbackup_unmount_command.html 
sidebar: sidebar 
keywords: run, backup, unmount, command, smo 
summary: backup unmount コマンドを実行して、バックアップをアンマウントできます。 
---
= smo backup unmount コマンドを使用します
:icons: font
:imagesdir: ../media/


[role="lead"]
backup unmount コマンドを実行して、バックアップをアンマウントできます。



== 構文

[listing]
----

        smo backup unmount
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id id\]
\[-force\]
\[-dump\]
\[-quiet \| -verbose\]
----


== パラメータ

* * -profile profile_name *
+
バックアップをアンマウントするプロファイルを指定します。プロファイルには、データベースの識別子およびその他のデータベース情報が含まれています。

* * -id id *
+
指定した GUID を持つバックアップをアンマウントします。GUID はバックアップを作成するときに SnapManager によって生成されます。各バックアップの GUID を表示する場合は、 smo backup list コマンドを使用します。

* * - ラベルラベル *
+
指定したラベルを持つバックアップをアンマウントします。

* *-data*
+
データファイルを指定します。

* *-archivelogs*
+
アーカイブログファイルを指定します。

* * -dump*
+
アンマウント処理が成功または失敗したあとにダンプファイルを収集します。

* * -force *
+
バックアップに関連付けられたリソースを解放する際に問題が発生した場合も、バックアップをアンマウントします。SnapManager がバックアップをアンマウントし、関連付けられているすべてのリソースをクリーンアップします。ログにアンマウント処理が正常に完了したことが記録されていますが、ログにエラーがある場合は、リソースを手動でクリーンアップしなければならないことがあります。

* * - Quiet *
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* * -verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。





== 例

次に、アンマウント処理の例を示します。

[listing]
----
# smo backup unmount -label test -profile SALES1 -verbose
----
[listing]
----
SMO-13046 [INFO ]: Operation GUID 8abc013111b909eb0111b90a02f50001 starting on Profile SALES1
SMO-08028 [INFO ]: Beginning to disconnect connected mount(s)
[/u/user1/mnt/_mnt_ssys1_logs_SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001,
 /u/user1/mnt/_mnt_ssys1_data_SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001].
SMO-08030 [INFO ]: Done disconnecting connected mount(s)
[/u/user1/mnt/_mnt_ssys1_logs_SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001,
 /u/user1/mnt/_mnt_ssys1_data_SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001].
SMO-13037 [INFO ]: Successfully completed operation: Backup Unmount
SMO-13048 [INFO ]: Operation Status: SUCCESS
SMO-13049 [INFO ]: Elapsed Time: 0:00:33.715
Operation Id [8abc013111b909eb0111b90a02f50001] succeeded.
----
* 関連情報 *

xref:task_unmounting_backups.adoc[バックアップのアンマウント]
