---
permalink: unix-administration/task_unmounting_backups.html 
sidebar: sidebar 
keywords: snapmanager, automatic, unmount, backup, unavailable, host, server, asm, smo 
summary: SnapManager は、バックアップを自動的にアンマウントして、ホストサーバで使用できないようにします。SnapManager では、 Oracle Recovery Manager\ （ RMAN \ ）などの外部ツールを使用してバックアップ内のファイルにアクセスしたり、バックアップの状態を変更してアクセスを切断したりすることもできます。 
---
= バックアップのアンマウント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager は、バックアップを自動的にアンマウントして、ホストサーバで使用できないようにします。SnapManager では、 Oracle Recovery Manager （ RMAN ）などの外部ツールを使用してバックアップ内のファイルにアクセスしたり、バックアップの状態を変更してアクセスを切断したりすることもできます。

リモートホストからデータベースバックアップをアンマウントする場合は、両方のホストで Automatic Storage Management （ ASM ）クレデンシャルが同じであることを確認する必要があります。

バックアップのアンマウント処理が成功した場合や失敗した場合に、ダンプファイルを収集することもできます。

マウントポイントがビジー状態の場合、 - [error] flow-11019 ： Failure in Disconnect:SD-10046 ：マウントポイントがビジー状態のためバックアップをアンマウントできません。この場合、マウントパスは次のマウントパスで使用中であり、 PID は /opt/NetApp/smt/mnt-Neverarch use nfs201995231995200903 PID を使用します。

アンマウント操作の失敗につながるセッションの PID を特定する必要があります。次のコマンドを実行して、セッションを停止します。 'kill pid'

これで、アンマウント処理を正常に実行できます。

. 次のコマンドを入力します。 `mo backup unmount -profile profile_name ｛ labelabel [data | -archivelogs ]|-idID ｝ [-quiet | -verbose -dump-force-verbose]


* 関連情報 *

xref:reference_the_smosmsapbackup_unmount_command.adoc[smo backup unmount コマンドを使用します]
