---
permalink: unix-administration/task_updating_profiles.html 
sidebar: sidebar 
keywords: update, profile, modify, password, number, backup, retain, access, database, operating, system, os, smo 
summary: プロファイルを更新して、プロファイル・パスワード、保持するバックアップ数、データベースへのアクセス、データベース認証に対するオペレーティング・システム認証（ OS ）、およびホストに関する情報を変更できます。Oracle データベースのパスワード情報が変更された場合は、プロファイル内のパスワード情報も変更する必要があります。 
---
= プロファイルの更新
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プロファイルを更新して、プロファイルのパスワード、保持するバックアップの数、データベースへのアクセス、データベース認証に対するオペレーティングシステム（ OS ）認証、およびホストに関する情報を変更できます。Oracle データベースのパスワード情報が変更された場合は、プロファイル内のパスワード情報も変更する必要があります。

プロファイルで保護ポリシーが有効になっている場合、 SnapManager を使用してポリシーを変更することはできません。ストレージ管理者は、 Protection Manager のコンソールを使用してポリシーを変更する必要があります。

SnapManager （ 3.2 以降）では、 Separe-archivelog-backups オプションを使用して、アーカイブログのバックアップをデータファイルのバックアップから分離するようにプロファイルを更新できます。アーカイブログバックアップには、別の保持期間および保護ポリシーを指定できます。SnapManager を使用すると、オンラインデータベースバックアップに加えてアーカイブログバックアップも含めることができます。また、オンラインのデータファイルバックアップとアーカイブログバックアップを一緒に作成してクローニングすることもできます。オンラインデータファイルバックアップを作成すると、アーカイブログバックアップがデータファイルとともにすぐに作成されます。

. 次のコマンドを入力します。 `mo profile update-profileprofileprofileprofileprofileprofile[-new-profileenew_profile_name] [-profile-password-password_password] [-datab_dbname -host db_host[-siddb_host] [-sidb_username -password db_password-durationsdb_port] -password-duration[-drman [-drman [--password-username -username] -username -usernamedbo -username -username -staname -username -username -username -stalumstaname -username -username -username -username -username -username -username -username -username -username -username -staname -username -usernamatummstalun [-drman [-drman [-drman [-drman [-drman [-drman [-drman [-drman [-drman [-drman [-drman [--password] -password] -password] -password] -username -username -username -username -username -username - email_address2-subjectsubjectsubject_pattern]]> [-separate -archivelog -backups-retain-archivelog -hourshours | -daysdays | -weeksmonths [-protect [-protection] [-protection-policypolicypolicy_name]|-nopresidle] [-one-backups-backups-nodump
+
このコマンドの他のオプションは、次のとおりです。

+
[-force] [-nopromp]

+
|===
| 状況 | 作業 


 a| 
* オペレーティング・システム認証を使用するようにプロファイルを変更します *
 a| 
ユーザ名、パスワード、およびポートを追加する代わりに、次の項目を指定します。

** -osaccountaccount_name をオペレーティングシステムアカウントの名前にします
** - オペレーティングシステムアカウントに関連付けられたグループとして osgroupgroup （通常は Oracle のインストールに使用されるアカウント）




 a| 
* 自動ストレージ管理（ ASM ）インスタンス認証を使用してプロファイルを作成します *
 a| 
ASM インスタンス認証のクレデンシャルを指定します。

** -asmusernameasminstance_username は、 ASM インスタンスへのログインに使用するユーザ名です。
** -asmpasswordasminstance_password は、 ASM インスタンスへのログインに使用するパスワードです。




 a| 
* カタログを Oracle Recovery Manager （ RMAN ）リポジトリとして使用するか、 RMAN * を削除します
 a| 
次のオプションと変数を指定します。

** -tnsname tnsname tnsname は、 tnsnames.ora ファイルで定義されている tnsname として指定します。
** - login - username username RMAN カタログへの接続に必要なユーザ名
+
指定しない場合、 SnapManager はオペレーティングシステムの認証情報を使用します。Real Application Clusters （ RAC ）データベースでは、オペレーティングシステム認証を使用できません。

** - RMAN カタログへの接続に必要な RMAN パスワードとして passwordpassword を使用します。
** - 制御ファイルを RMAN リポジトリとして使用する場合、制御ファイル
** -remove-rman を使用して RMAN を削除します。




 a| 
* プロファイル * で、データベースのバックアップのバックアップ保持ポリシーを変更します
 a| 
保持ポリシーを変更するには、保持クラスの保持数または保持期間、あるいはその両方を指定します。期間はクラスの単位で指定します（たとえば、時間単位の場合は時間単位、日単位の場合は日単位）。

** -hourly は、時間単位の保持クラスです。 [-countn] [-durationm] は、それぞれ保持数および保持期間です。
** -daily は、日単位の保持クラスです。 [-countn] [-durationm] は、それぞれ保持数と保持期間です。
** -weekly は週単位の保持クラスであり、 [-countn] [-durationm] はそれぞれ保持数および保持期間です。
** -monthly は月単位の保持クラスです。 [-countn] [-durationm] は、それぞれ保持数および保持期間です。




 a| 
* プロファイルのバックアップ保護を無効にします *
 a| 
プロファイルを使用して作成されたデータベース・バックアップを保護しない場合は、 -nobprotect を指定します。保護が有効になっているプロファイルで保護を無効にすると、データセットが削除され、このプロファイルのバックアップをリストアまたはクローニングできないことを示す警告メッセージが表示されます。



 a| 
* データベース操作の完了ステータスの電子メール通知を有効にします *
 a| 
次のオプションと変数を指定します。

** -summary-notification を使用すると、リポジトリデータベース内の複数のプロファイルについて、サマリー E メール通知を設定できます。
** -notification を使用すると、プロファイルのデータベース処理の完了ステータスに関する E メール通知を受信できます。
** -success -email_address2 を使用すると、新規または既存のプロファイルを使用して正常に実行されたデータベース処理の完了後に、 E メール通知を受け取ることができます。
** -failure-email_address2 を使用すると、新規または既存のプロファイルを使用して実行されたデータベース処理に失敗した場合に、 E メール通知を受け取ることができます。
** -subjectsubjectsub_text ：新しいプロファイルまたは既存のプロファイルを作成する際の E メール通知の件名を指定します。リポジトリに対して通知設定が設定されておらず、コマンドラインインターフェイス（ CLI ）を使用してプロファイル通知または要約通知を設定しようとしている場合、コンソールログに次のメッセージが記録されます。 SMO-14577 ：通知設定が設定されていません。
+
通知設定を構成したあとに、リポジトリのサマリー通知を有効にせずに CLI を使用してサマリー通知を設定しようとすると、コンソールログに次のメッセージが記録されます。 SMO-14575 ： Summary notification configuration not available for this repository_**__





 a| 
* プロファイルを更新して、アーカイブ・ログ・ファイルのバックアップを個別に作成します。 *
 a| 
次のオプションと変数を指定します。

** -separate-archivelog バックアップを使用すると、データベース・ファイルとは別にアーカイブ・ログ・ファイルのバックアップを作成できます。
+
このオプションを指定すると、データファイルのみのバックアップまたはアーカイブログのみのバックアップを作成できます。フルバックアップは作成できません。また、バックアップを分離してプロファイル設定を元に戻すこともできません。SnapManager では、アーカイブログのみのバックアップを作成する前に作成されたバックアップの保持ポリシーに基づいてバックアップが保持されます。

** -retain-archivedlog backups ：アーカイブログのバックアップの保存期間を設定します。
+

NOTE: 初めてプロファイルを更新する場合は、 -separate archivedlog-backups オプションを使用して、アーカイブログのバックアップをデータファイルのバックアップから分離できます。 -retain-archivelog backups オプションを使用して、アーカイブログのバックアップの保持期間を指定する必要があります。プロファイルをあとで更新する場合、保持期間の設定は任意です。

** - Protect は、 Data Fabric Manager （ DFM ）サーバにアプリケーションデータセットを作成し、データベース、データファイル、制御ファイル、およびアーカイブログに関連するメンバーを追加します。
+
データセットが存在する場合は、プロファイルの作成時にデータセットが再利用されます。

** -protection-policy は、保護ポリシーをアーカイブログバックアップに設定します。
** includee-with -one-backups ：アーカイブログのバックアップをデータベースのバックアップとともに格納するように指定します。
** -no-inclu他 の -one-backups ：アーカイブログファイルのバックアップがデータベースバックアップに含まれないことを指定します。




 a| 
* ターゲット・データベースのホスト名を変更します *
 a| 
プロファイルのホスト名を変更するには、 -hostnew_db_host を指定します。



 a| 
* プロファイルの更新処理後にダンプ・ファイルを収集 *
 a| 
dump オプションを指定します。

|===
. 更新されたプロファイルを表示するには、次のコマンドを入力します。 'mo profile show'


* 関連情報 *

xref:concept_how_to_collect_dump_files.adoc[ダンプ・ファイルの収集方法]
