---
permalink: unix-administration/task_using_snapmanager_for_oracle_to_create_the_database_profile_for_a_local_backup.html 
sidebar: sidebar 
keywords: database, administrator, snapmanager, create, profile, backup, local, oracle 
summary: データベース管理者は、 SnapManager を使用してデータベースプロファイルを作成し、プライマリストレージシステム上のローカルストレージへのバックアップを開始します。プロファイルの作成プロセスとバックアップ作成プロセスはすべて SnapManager で実行され、 Protection Manager も含まれません。 
---
= SnapManager for Oracle を使用して、ローカル・バックアップのデータベース・プロファイルを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データベース管理者は、 SnapManager を使用してデータベースプロファイルを作成し、プライマリストレージシステム上のローカルストレージへのバックアップを開始します。プロファイルの作成プロセスとバックアップ作成プロセスはすべて SnapManager で実行され、 Protection Manager も含まれません。

プロファイルには、クレデンシャル、バックアップの設定、バックアップの保護設定など、管理対象のデータベースに関する情報が含まれます。プロファイルを作成すると、そのデータベースに対して処理を実行するたびにデータベースの詳細を指定する必要がなくなり、プロファイル名を指定するだけで済みます。1 つのプロファイルが参照できるデータベースは 1 つだけです。同じデータベースは、複数のプロファイルから参照できます。

. SnapManager for Oracle クライアントにアクセスします。
. SnapManager リポジトリツリーで、このプロファイルに関連付けるホストを右クリックし、 * プロファイルの作成 * を選択します。
. [Profile Configuration Information] ページで、次の情報を入力し、 [Next] をクリックします。
+
** プロファイル名： payroll_prod
** プロファイルパスワード： payroll123
** コメント： Production Payroll データベース


. Database Configuration Information （データベース設定情報）ページで、次の情報を入力し、 * Next （次へ） * をクリックします。
+
** データベース名： PAYDB
** データベース SID ： payrolldb
** Database host ：デフォルトの設定をそのまま使用します
+
リポジトリツリー内のホストからプロファイルを作成しているため、 SnapManager にホスト名が表示されます。



. 2 番目の Database Configuration Information ページで、次のデータベース情報を受け入れ、 * Next * をクリックします。
+
** Oracle ユーザアカウントであるホストアカウント： oracle
** ホストグループ。 Oracle グループの場合は、 dba です


. [ データベース接続情報 ] ページで、 [ データベース認証を使用 ] を選択して、ユーザーがデータベース情報を使用して認証できるようにします。
+
この例では、次の情報を入力し、 * 次へ * をクリックします。

+
** Administrator 権限を持つシステム・データベース管理者である sys を表す SYSDBA 特権ユーザ名
** パスワード（ SYSDBA パスワード）： oracle
** データベース・ホストに接続するポート： 1521


. [RMAN 構成情報 ] ページで、 [* Do not use RMAN* ] を選択し、 [ 次へ ] をクリックします。
+
Oracle Recovery Manager （ RMAN ）は、ブロックレベルの検出機能を使用して Oracle データベースのバックアップとリカバリを行うための Oracle ツールです。

. スナップショットの命名情報ページで、変数を選択して、このプロファイルに関連付けられたスナップショットの命名規則を指定します。必要な唯一の変数は *smid* 変数で、一意のスナップショット識別子が作成されます。
+
この例では、次の手順を実行します。

+
.. [ 変数トークン ] リストで、 * ｛ usertext ｝ * 変数を選択し、 [ * 追加 ] をクリックします。
.. ホスト名として「 payroll.techco.com_" 」と入力し、「 * OK 」をクリックします。
.. 形式ボックスの「 smo 」の直後にホスト名が表示されるまで、 * left * をクリックします。
.. 「 * 次へ * 」をクリックします。


+
smo _hostname_smosprof_dbsid_scope_mode_smid の Snapshot 命名規則は smo_payroll.techco.com_payroll_prod2_payrolldb_f_a_x" になります（「 f 」はフル・バックアップ、「 A 」は自動モード、「 x 」は一意の SMID を表します）。

. [ 操作の実行 ] ページで、情報を確認し、 [ * 作成 ] をクリックします。
. [* Operation Details] をクリックして、プロファイル作成処理およびボリューム・ベースのリストアの適格性情報を表示します。

