---
permalink: unix-administration/task_creating_clone_specifications.html 
sidebar: sidebar 
keywords: snapmanager, oracle, clone, specification, xml, file, mapping, option, parameter, creating 
summary: SnapManager for Oracle では、クローン仕様 XML ファイルを使用します。このファイルには、クローン処理で使用するマッピング、オプション、およびパラメータが含まれています。SnapManager は、この情報を使用して、クローニングするファイルの配置場所、および診断情報、制御ファイル、パラメータなどの処理方法を決定します。 
---
= クローン仕様を作成しています
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager for Oracle では、クローン仕様 XML ファイルを使用します。このファイルには、クローン処理で使用するマッピング、オプション、およびパラメータが含まれています。SnapManager は、この情報を使用して、クローニングするファイルの配置場所、および診断情報、制御ファイル、パラメータなどの処理方法を決定します。

クローン仕様ファイルは、 SnapManager のグラフィカルユーザインターフェイス（ GUI ）、コマンドラインインターフェイス（ CLI ）、またはテキストエディタを使用して作成できます。

テキストエディタを使用してクローン仕様ファイルを作成する場合は、 .xml ファイルとして保存する必要があります。この XML ファイルは、他のクローニング処理に使用できます。

クローン仕様テンプレートを作成し、カスタマイズすることもできます。smo clone template コマンドを使用するか、 GUI で Clone ウィザードを使用します。

SnapManager for Oracle では、生成されるクローン仕様テンプレートにバージョン文字列が追加されます。SnapManager for Oracle は、バージョン文字列がないクローン仕様ファイルの最新バージョンを前提としています。

リモートクローニングを実行する場合は、クローン仕様ファイル内のデータファイル、 REDO ログファイル、および制御ファイルのデフォルトの場所を変更しないでください。デフォルトの場所を変更した場合、 SnapManager は、 Snapshot 機能をサポートしていないデータベース上でクローンの作成に失敗するか、クローンを作成しません。そのため、プロファイルの自動作成は失敗します。


NOTE: マウントポイントと ASM ディスクグループの情報は GUI から編集できますが、変更できるのはファイル名のみで、ファイルの場所は変更できません。

同じパラメータと値の組み合わせを使用して、タスクを複数回実行できます。

. テキストファイルを開き、次の例に示すようにテキストを入力します。
+
[listing]
----
<clone-specification xmlns="http://www.example.com>
     <storage-specification/>
     <database-specification/>
 </clone-specification>
----
. ストレージ仕様コンポーネントで、データファイルのマウントポイントを入力します。
+
ストレージ仕様には、データ・ファイルのマウント・ポイントや raw デバイスなど、クローン用に作成された新しいストレージの場所が表示されます。これらの項目は、ソースからデスティネーションにマッピングする必要があります。

+
次に、クローン仕様で使用するデータ・ファイル・マウント・ポイントの構文の例を示します。

+
[listing]
----
<mountpoint>
     <source>/mnt/path/source_data file_mountpoint</source>
     <destination>/mnt/path/target_data file_mountpoint</destination>
</mountpoint>
----
. オプション：ソース上に raw デバイスがある場合は、ソース上の raw デバイスのパスを指定し、デスティネーションに対して destination auto-generate= "true" を指定する必要があります。
+
以前のバージョンの SnapManager for Oracle のクローン・マッピング・ファイルとは異なり、デスティネーション上の raw デバイスの場所は指定できません。クローニングされた raw デバイスについては、 SnapManager for Oracle で次に使用可能なデバイス名が選択されます。

+
次に、クローン仕様で使用する raw デバイスの構文を表示する例を示します。

+
[listing]
----
<raw-device>
     <source>/dev/raw/raw1</source>
     <destination auto-generate="true"/>
</raw-device>
----
. データベース仕様コンポーネントで、制御ファイルの情報を、クローン用に作成する制御ファイルのリストとして指定します。
+
データベース仕様では、制御ファイル、 REDO ログ、アーカイブ・ログ、 Oracle パラメータなど、クローンのデータベース・オプションを指定しています。

+
次に、クローン仕様で使用する制御ファイルの構文の例を示します。

+
[listing]
----
<controlfiles>
     <file>/mnt/path/clonename/control/control01.ctl</file>
     <file>/mnt/path/clonename/control/control02.ctl</file>
</controlfiles>
----
. クローンの REDO ログ構造を指定します。
+
次に、クローニングの REDO ログディレクトリの構造を表示する例を示します。

+
[listing]
----
<redologs>
     <redogroup>
          <file>/mnt/path/clonename/redo/redo01.log</file>
          <number>1</number>
          <size unit="M">100</size>
     </redogroup>
     <redogroup>
         <file>/mnt/path/clonename/redo/redo02.log</file>
         <number>2</number>
         <size unit="M">100</size>
     </redogroup>
</redologs>
----
. クローニングしたデータベースで、別の値に設定する Oracle パラメータを指定します。Oracle 10 を使用している場合は、次のパラメータを指定する必要があります。
+
** バックグラウンド・ダンプ
** コアダンプ
** ユーザダンプ
** （オプション）ログをアーカイブします
+

NOTE: パラメータ値が正しく設定されていないとクローニング処理が停止し、エラーメッセージが表示されます。



+
アーカイブログの格納場所を指定しない場合、 SnapManager は NOARCHIVELOG モードでクローンを作成します。SnapManager は、このパラメータ情報をクローンの init.ora ファイルにコピーします。

+
+ 次の例は、クローン仕様で使用するパラメータ構文を示しています。

+
[+]

+
[listing]
----
<parameters>
     <parameter>
          <name>log_archive_dest_1</name>
          <value>LOCATION=/mnt/path/clonename/archive</value>
     </parameter>
</parameters>
----
+
+ デフォルト値を使用するには、パラメータ要素内で default 要素を使用します。次の例では、デフォルトの要素が指定されているため、 os_authentication_prefix パラメータでデフォルト値が使用されます。

+
[+]

+
[listing]
----
<parameters>
     <parameter>
          <name>os_authent_prefix</name>
          <default></default>
     </parameter>
</parameters>
----
+
+ 空の要素を使用して、パラメータの値として空の文字列を指定できます。次の例では、 os_authentication_prefix が空の文字列に設定されます。

+
[+]

+
[listing]
----
<parameters>
     <parameter>
          <name>os_authent_prefix</name>
          <value></value>
     </parameter>
</parameters>
----
+
+ 注 : ソースデータベースの init.ora ファイルの値は、エレメントを指定せずにパラメータに使用できます。

+
+ パラメータに複数の値がある場合は、パラメータ値をカンマで区切って指定できます。たとえば、ある場所から別の場所にデータファイルを移動する場合は、 db_file_name _convert パラメータを使用し、データファイルパスをカンマで区切って指定できます。次に例を示します。

+
[+]

+
[listing]
----
<parameters>
     <parameter>
          <name>db_file_name_convert</name>
          <value>>/mnt/path/clonename/data file1,/mnt/path/clonename/data file2</value>
     </parameter>
</parameters>
----
+
+ ログファイルを別の場所に移動する場合は、次の例に示すように、 log_file_name _convert パラメータを使用して、ログファイルのパスをカンマで区切って指定します。

+
[+]

+
[listing]
----
<parameters>
     <parameter>
          <name>log_file_name_convert</name>
          <value>>/mnt/path/clonename/archivle1,/mnt/path/clonename/archivle2</value>
     </parameter>
</parameters>
----
. オプション：任意の SQL ステートメントを指定し、クローンがオンラインのときにそのステートメントを実行します。
+
SQL ステートメントを使用すると、クローニングされたデータベース内で一時ファイルを再作成するなどのタスクを実行できます。

+

NOTE: SQL ステートメントの最後にセミコロンが含まれていないことを確認してください。

+
次に、クローニング処理の一環として実行する SQL ステートメントの例を示します。

+
[listing]
----
<sql-statements>
   <sql-statement>
     ALTER TABLESPACE TEMP ADD
     TEMPFILE '/mnt/path/clonename/temp_user01.dbf'
     SIZE 41943040 REUSE AUTOEXTEND ON NEXT 655360
     MAXSIZE 32767M
   </sql-statement>
</sql-statements>
----




== クローン仕様の例

次に、ストレージおよびデータベース仕様の両方のコンポーネントを含む、クローン仕様の構造を表示する例を示します。

[listing]
----
<clone-specification xmlns="http://www.example.com>

   <storage-specification>
     <storage-mapping>
        <mountpoint>
          <source>/mnt/path/source_mountpoint</source>
          <destination>/mnt/path/target_mountpoint</destination>
        </mountpoint>
        <raw-device>
          <source>/dev/raw/raw1</source>
          <destination auto-generate="true"/>
        </raw-device>
        <raw-device>
          <source>/dev/raw/raw2</source>
          <destination auto-generate="true"/>
        </raw-device>
     </storage-mapping>
   </storage-specification>

   <database-specification>
     <controlfiles>
       <file>/mnt/path/clonename/control/control01.ctl</file>
       <file>/mnt/path/clonename/control/control02.ctl</file>
     </controlfiles>
     <redologs>
         <redogroup>
           <file>/mnt/path/clonename/redo/redo01.log</file>
           <number>1</number>
           <size unit="M">100</size>
        </redogroup>
        <redogroup>
           <file>/mnt/path/clonename/redo/redo02.log</file>
           <number>2</number>
           <size unit="M">100</size>
        </redogroup>
    </redologs>
    <parameters>
      <parameter>
        <name>log_archive_dest_1</name>
        <value>LOCATION=/mnt/path/clonename/archive</value>
      </parameter>
      <parameter>
        <name>background_dump_dest</name>
        <value>/mnt/path/clonename/admin/bdump</value>
      </parameter>
      <parameter>
        <name>core_dump_dest</name>
        <value>/mnt/path/clonename/admin/cdump</value>
      </parameter>
      <parameter>
        <name>user_dump_dest</name>
        <value>/mnt/path/clonename/admin/udump</value>
      </parameter>
    </parameters>
   </database-specification>
</clone-specification>
----
* 関連情報 *

xref:task_cloning_databases_and_using_custom_plugin_scripts.adoc[データベースのクローニングおよびカスタムプラグインスクリプトの使用]

xref:task_cloning_databases_from_backups.adoc[バックアップからデータベースをクローニングする]

xref:task_cloning_databases_in_the_current_state.adoc[現在の状態のデータベースをクローニングしています]

xref:concept_considerations_for_cloning_a_database_to_an_alternate_host.adoc[代替ホストにデータベースをクローニングする場合の考慮事項]
