---
permalink: unix-administration/task_use_snapmanager_for_oracle_to_restore_a_local_backup_on_primary_storage.html 
sidebar: sidebar 
keywords: restore, local, backup, exist, primary, storage, entire, process, perform, snapmanager, oracle, 
summary: プライマリストレージにあるローカルバックアップをリストアすることができます。プロセス全体は、 SnapManager for Oracle を使用して実行されます。 
---
= SnapManager for Oracle を使用してプライマリストレージ上のローカルバックアップをリストアする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プライマリストレージにあるローカルバックアップをリストアすることができます。プロセス全体は、 SnapManager for Oracle を使用して実行されます。

バックアップのリストアプロセスに関する情報をプレビューすることもできます。この操作を実行すると、バックアップのリストア対応に関する情報を確認できます。SnapManager はバックアップのデータを分析し、ボリュームベースのリストアまたはファイルベースのリストア方式を使用してリストアプロセスを完了できるかどうかを判断します。

リストアプレビューには次の情報が表示されます。

* 各ファイルのリストアに使用するリストアメカニズム（高速リストア、ストレージ側のファイルシステムのリストア、ストレージ側のファイルのリストア、またはホスト側のファイルコピーのリストア）
* 各ファイルのリストアに、より効率的なメカニズムが使用されなかった理由。


リストア計画のプレビューでは、 SnapManager は何もリストアしません。プレビューには、 20 ファイルまでの情報が表示されます。

データファイルのリストアをプレビューする際に、データベースがマウントされていない場合は、 SnapManager によってデータベースがマウントされます。データベースをマウントできない場合、処理は失敗し、 SnapManager はデータベースを元の状態に戻します。

. リポジトリ・ツリーで、リストアするバックアップを右クリックし、 * リストア * を選択します。
. [ リストアとリカバリウィザード ] の [ ようこそ ] ページで、 [ 次へ ] をクリックします。
. [ 構成情報の復元 ] ページで、 [ * データファイル / テーブルスペースの完全な復元と制御ファイル * ] を選択します。
. [ 必要に応じてデータベースのシャットダウンを許可する ] をクリックします。 *
+
SnapManager は、必要に応じてデータベースの状態を変更します。たとえば、データベースがオフラインでオンラインにする必要がある場合、 SnapManager によってデータベースが強制的にオンラインに切り替えられます。

. [ リカバリ構成情報 ] ページで、 [ * すべてのログ * ] をクリックします。
+
SnapManager は、データベースを最後のトランザクションまでリストアおよびリカバリし、必要なすべてのログを適用します。

. [Restore Source Location Configuration] ページで、プライマリのバックアップに関する情報を表示し、 [Next] をクリックします。
+
バックアップがプライマリストレージ上にのみ存在する場合、 SnapManager はプライマリストレージからバックアップをリストアします。

. Volume Restore Configuration Information （ボリューム復元設定情報）ページで、 * Attempt volume restore （ボリューム復元の試行） * を選択して、ボリューム復元方法を試みます。
. [ ファイルベースの復元へのフォールバック * ] をクリックします。
+
これにより、ボリュームのリストア方式を使用できない場合でも、 SnapManager でファイルベースのリストア方式を使用できます。

. [* Preview] をクリックして、高速リストアの資格チェックと、必須およびオーバーライド可能なチェックに関する情報を表示します。
. [ 操作の実行 ] ページで、入力した情報を確認し、 [* リストア * ] をクリックします。
. プロセスの詳細を表示するには、 [* 操作の詳細 * ] をクリックします。

