---
permalink: unix-administration/task_previewing_backup_restore_information.html 
sidebar: sidebar 
keywords: preview, information, backup, restore, process, occurs, eligibility, storage-side, fast, file 
summary: バックアップのリストアプロセスが実行される前に、そのプロセスに関する情報をプレビューして、 SnapManager for Oracle がバックアップで検出したリストア対応状況を確認できます。SnapManager はバックアップ上のデータを分析して、リストアプロセスを正常に完了できるかどうかを判断します。 
---
= バックアップリストア情報をプレビューしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップのリストアプロセスが実行される前に、そのプロセスに関する情報をプレビューして、 SnapManager for Oracle がバックアップで検出したリストア対応状況を確認できます。SnapManager はバックアップ上のデータを分析して、リストアプロセスを正常に完了できるかどうかを判断します。

リストアプレビューでは次の情報を確認できます。

* 各ファイルのリストアに使用できるリストアメカニズム（高速リストア、ストレージ側のファイルシステムのリストア、ストレージ側のファイルのリストア、またはホスト側のファイルコピーのリストア）
* verbose オプションを指定すると、各ファイルのリストアに効率的なメカニズムが使用されなかった理由が表示されます。


backup restore コマンドに -preview オプションを指定すると、 SnapManager は何もリストアしませんが、リストア対象のファイルとリストア方法が表示されます。


NOTE: すべてのタイプのリストアメカニズムをプレビューできます。プレビューには、最大 20 個のファイルに関する情報が表示されます。

. 次のコマンドを入力します。 smo backup restore -profile profile_name -labellabel -complete -preview -verbose
+
たとえば、次のように入力します。

+
[listing]
----
smo backup restore -profile targetdb1_prof1
      -label full_bkup_sales_nov_08  -complete -preview -verbose
----
+
次に、ホスト側のファイルコピーリストアプロセスを使用してリストアされるファイルと、高速リストアオプションを使用してリストアできないファイルの例を示します。verbose オプションを指定すると、 SnapManager のプレビュー・セクションと分析セクションに、高速リストア・プロセスで各ファイルをリストアできない理由が表示されます。

+
[listing]
----
PREVIEW:
The following files will be restored via host side file copy restore:
+DG2/sid/datafile10.dbf
+DG2/sid/datafile11.dbf

ANALYSIS:
The following reasons prevent certain files from being restored via fast restore:
Reasons:
 Newer snapshots of /vol/volume2 have volume clones: SNAP_1
*Newer backups will be freed: nightly2, nightly3
Files to Restore:
/mnt/systemB/volume2/system.dbf
/mnt/systemB/volume2/users.dbf
/mnt/systemB/volume2/sysaux.dbf
/mnt/systemB/volume2/datafile04.dbf
/mnt/systemB/volume2/datafile05.dbf

The following reasons prevent certain files from being restored via fast restore:
Reasons:
* Newer snapshots of /vol/adm_disks will be lost: ADM_SNAP_5
* Luns present which were created after snapshot SNAP_0 was created: /vol/adm_disks/disk5.lun
* Files not part of the restore scope will be reverted in file system: +DG2

Files Not in Restore Scope: +DG2/someothersid/data01.dbf
+DG2/someothersid/data02.dbf
Files to Restore:
+DG2/sid/datafile08.dbf +DG2/sid/datafile09.dbf
+DG2/sid/datafile10.dbf +DG2/sid/datafile11.dbf

* Reasons denoted with an asterisk (*) are overridable.
----
. 他のリストア・プロセスを使用できない理由を確認します。
. 上書き可能な理由だけが表示される場合は、 -preview オプションを使用せずにリストア処理を開始します。
+
必須でないチェックは無視してもかまいません。


