---
permalink: unix-administration/task_setting_credentials_after_clearing_credential_cache.html 
sidebar: sidebar 
keywords: clear, cache, remove, store, user, credentials, host, repositories, profile, credential 
summary: キャッシュをクリアして格納されているユーザクレデンシャルを削除したら、ホスト、リポジトリ、およびプロファイルのクレデンシャルを設定できます。 
---
= クレデンシャルキャッシュをクリアしたあとにクレデンシャルを設定
:icons: font
:imagesdir: ../media/


[role="lead"]
キャッシュをクリアして格納されているユーザクレデンシャルを削除したら、ホスト、リポジトリ、およびプロファイルのクレデンシャルを設定できます。

リポジトリ、プロファイルホスト、およびプロファイルには、以前に指定したのと同じユーザクレデンシャルを設定する必要があります。ユーザクレデンシャルの設定時に暗号化されたクレデンシャルファイルが作成されます。

クレデンシャルファイルは、 /root/.netapp / smo /3.3.0 にあります。

SnapManager GUI （グラフィカルユーザーインタフェース）で、リポジトリにリポジトリがない場合は、次の手順を実行します。

. 既存のリポジトリを追加するには '[ タスク *>] → [ 既存のリポジトリの追加 ] をクリックします
. リポジトリのクレデンシャルを設定するには、次の手順を実行します。
+
.. リポジトリを右クリックし '[* 開く *] を選択します
.. Repository Credentials Authentication ウィンドウで、ユーザクレデンシャルを入力します。


. ホストのクレデンシャルを設定するには、次の手順を実行します。
+
.. リポジトリの下のホストを右クリックし '[*Open*] を選択します
.. Host Credentials Authentication ウィンドウで、ユーザクレデンシャルを入力します。


. プロファイルのクレデンシャルを設定するには、次の手順を実行します。
+
.. ホストの下のプロファイルを右クリックし、 * 開く * を選択します。
.. [Profile Credentials Authentication] ウィンドウで、ユーザクレデンシャルを入力します。



