---
permalink: unix-administration/task_resetting_profile_password.html 
sidebar: sidebar 
keywords: reset, profile, password, remember, creating, snapmanager, credentials, cli, smo 
summary: プロファイルの作成時に指定したパスワードがわからない場合は、プロファイルのパスワードをリセットできます。 
---
= プロファイルパスワードをリセットしています
:icons: font
:imagesdir: ../media/


[role="lead"]
プロファイルの作成時に指定したパスワードがわからない場合は、プロファイルのパスワードをリセットできます。

* SnapManager サーバがリポジトリデータベースで実行されていることを確認する必要があります。
* リポジトリデータベースが格納されているホストの root ユーザのクレデンシャルが必要です。
* プロファイルのパスワードをリセットするときは、そのプロファイルがどの処理でも使用されていないことを確認してください。


パスワードは、 SnapManager の CLI または GUI からリセットできます。パスワードをリセットする際に、 SnapManager はリポジトリホスト上の SnapManager サーバを照会して、リポジトリホストのオペレーティングシステムを特定します。リポジトリホストに接続するための、許可されたユーザクレデンシャルを入力する必要があります。SnapManager サーバは、リポジトリデータベースのルートクレデンシャルを使用してユーザを認証します。認証が成功すると、 SnapManager は SnapManager サーバのプロファイルパスワードを新しいパスワードでリセットします。


NOTE: SnapManager は、パスワードのリセット操作の履歴を保持しません。

. 次のコマンドを入力して、プロファイルパスワードをリセットします。 'mo password reset-profile [-profile-passwordprofile_password] [-repository -hostadmin-passwordadmin_password] '

