---
permalink: unix-administration/task_changing_the_retention_policy_default_behavior.html 
sidebar: sidebar 
keywords: backup, expire, based, retention, policy, snapmanager, determine, delete, backup, setting, policy, default, behavior 
summary: 保持ポリシーに基づいてバックアップが期限切れになると、 SnapManager は保持設定に基づいてバックアップを削除するかどうかを決定します。デフォルトでは、バックアップの削除が実行されます。このデフォルトの動作を変更して、保護されていないバックアップを解放するように選択できます。 
---
= 保持ポリシーのデフォルト動作を変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
保持ポリシーに基づいてバックアップが期限切れになると、 SnapManager は保持設定に基づいてバックアップを削除するかどうかを決定します。デフォルトでは、バックアップの削除が実行されます。このデフォルトの動作を変更して、保護されていないバックアップを解放するように選択できます。

デフォルトでは、 SnapManager は、保護されているかどうかに応じて、バックアップを削除するか、解放します。

* 保護されたバックアップでは、 SnapManager が期限切れになるとローカルバックアップを解放します。
* 保護されていないバックアップの場合、 SnapManager は有効期限が切れた時点でローカルバックアップを削除します。
+
このデフォルトの動作は変更できます。



保護されたバックアップについては、 SnapManager でローカルコピーを削除するかどうかを判断する際に次の点が考慮されません。

* セカンダリストレージへのバックアップに失敗したか、または保護処理中です。
+
これにより、保持ポリシーが適用される前に、セカンダリストレージにバックアップを転送できるようになります。

* その後、セカンダリストレージからコピーが削除された。
+
.. 次のデフォルトの場所にアクセスします。
+
smo installation location /properties/ smo .config のデフォルト値

.. smo .config ファイルを編集します。
.. smo .config ファイルの retain.alwaysFreeExpiredBackups プロパティを true に設定します。
+
たとえば、 retain.alwaysFreeExpiredBackups = true となります





* 関連情報 *

xref:reference_the_smosmsapbackup_update_command.adoc[smo backup update コマンド]
