---
permalink: unix-installation-cmode/concept_understanding_the_differences_between_snapmirror_and_snapvault.html 
sidebar: sidebar 
keywords: snapmirror, disaster, recovery, technology, design, failover, primary, storage, secondary, geographically, disk-to-disk, snapshot, copy, replication, governance-related, purpose, compliance, standard 
summary: SnapMirror は、地理的に離れたサイトのプライマリストレージからセカンダリストレージへのフェイルオーバー用に設計されたディザスタリカバリテクノロジです。SnapVault は、基準への準拠およびその他のガバナンス関連の目的で、ディスクツーディスクの Snapshot コピーレプリケーション用に設計されたアーカイブテクノロジです。 
---
= SnapMirror と SnapVault の違いを理解する
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror は、地理的に離れたサイトのプライマリストレージからセカンダリストレージへのフェイルオーバー用に設計されたディザスタリカバリテクノロジです。SnapVault は、基準への準拠およびその他のガバナンス関連の目的で、ディスクツーディスクの Snapshot コピーレプリケーション用に設計されたアーカイブテクノロジです。

このような目的の違いにより、各テクノロジがバックアップの有効期間とバックアップの保持の目標を両立させる際にも違いが生じます。

* SnapMirror Stores _Only - プライマリストレージにある Snapshot コピー。災害が発生した場合に備えて、適切な状態の最新バージョンのプライマリデータをフェイルオーバーできる必要があります。たとえば、組織では、 10 日間にわたって本番データのコピーを 1 時間ごとにミラーリングしなければならない場合があります。フェイルオーバーの事例で示すように、ミラーリングされたストレージからデータを効率的に提供するには、セカンダリシステム上の機器がプライマリシステム上の機器と同じであるか、ほぼ同じである必要があります。
* 一方、 SnapVault は、 Snapshot コピーが現在プライマリストレージにあるかどうかに関係なく、 Snapshot コピーを格納します。これは、監査の際、履歴データへのアクセスが現在のデータへのアクセスと同様に重要になる可能性があるためです。場合によっては、月間のデータの Snapshot コピーを 20 年間にわたって保持しなければならないことがあります（たとえば、ビジネスに関する政府会計規則に準拠するためなど）。セカンダリストレージからデータを提供するための要件は存在しないため、 SnapVault システムでは低速かつ低コストのディスクを使用できます。


もちろん、 SnapMirror と SnapVault がバックアップの有効期間およびバックアップの保持に設定する重みの違いは、最終的には、各ボリュームの Snapshot コピー数が 255 個に制限されていることに由来します。SnapMirror は最新のコピーを保持し、 SnapVault は最長期間にわたって作成されたコピーを保持します。
