---
permalink: unix-installation-cmode/delete_reference_trademark.html 
sidebar: sidebar 
keywords: trademark, information 
summary: 商標に関する情報 
---
= 商標に関する情報
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


NetApp、 NetAppロゴ、Go Further、Faster、 AltaVault、ASUP、 AutoSupport、Campaign Express、Cloud ONTAP、Clustered Data ONTAP、Customer Fitness、 Data ONTAP、DataMotion、Fitness、 Flash Accel、Flash Cache、Flash Pool、FlashRay、 FlexCache、 FlexClone、 FlexPod、FlexScale、FlexShare、 FlexVol、FPolicy、GetSuccessful、LockVault、Manage ONTAP、Mars、 MetroCluster、 MultiStore、 NetApp Insight、 OnCommand、 ONTAP、ONTAPI、 RAID DP、 RAID-TEC、 SANtricity、 SecureShare、Simplicity、Simulate ONTAP、Snap Creator、 SnapCenter、 SnapCopy、 SnapDrive、 SnapIntegrator、 SnapLock、 SnapManager、 SnapMirror、 SnapMover、 SnapProtect、 SnapRestore、Snapshot、 SnapValidator、 SnapVault、 StorageGRID、 Tech OnTap、Unbound Cloud、 WAFLおよびその他の名前は、米国およびその他の国におけるNetApp, Inc. の商標または登録商標です。その他のすべてのブランドまたは製品は、それぞれの所有者の商標または登録商標であり、そのように扱われる必要があります。  NetAppの商標の最新リストは、以下のWebサイトでご覧いただけます。 http://www.netapp.com/us/legal/netapptmlist.aspx[] 。
