---
permalink: unix-installation-7mode/task_backing_up_your_database.html 
sidebar: sidebar 
keywords: creating, profile, database, schedule, initial, backup, verification, unix 
summary: プロファイルの作成後、データベースをバックアップする必要があります。初期バックアップおよび検証のあとに、定期的なバックアップのスケジュールを設定できます。 
---
= データベースをバックアップしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プロファイルの作成後、データベースをバックアップする必要があります。初期バックアップおよび検証のあとに、定期的なバックアップのスケジュールを設定できます。

以下の手順では、 SnapManager ユーザインターフェイスを使用してデータベースのバックアップを作成する方法を示します。必要に応じて、コマンドラインインターフェイス（ CLI ）を使用することもできます。

CLI を使用してバックアップを作成する方法については、『 SnapManager for Oracle アドミニストレーションガイド UNIX_ 』を参照してください。

. [ リポジトリ ] ツリーで、バックアップするデータベースを含むプロファイルを右クリックし、 [ * バックアップ * ] を選択します。
. 「 * Label * 」に、バックアップのカスタム名を入力します。
+
名前にスペースや特殊文字を含めることはできません。バックアップ・ラベルは、名前を指定しないと SnapManager によって自動的に作成されます。

+
SnapManager 3.4 から、 SnapManager によって自動的に作成されたバックアップラベルを変更できます。override.default.backup.pattern および new.default.backup.pattern の設定変数を編集して、独自のデフォルトのバックアップラベルパターンを作成できます。

. 必要に応じてデータベースの状態を変更するには、 [ 必要に応じてデータベースの起動またはシャットダウンを許可する ] を選択します。
+
このオプションにより、バックアップを作成するためにデータベースが必須状態でない場合、 SnapManager は自動的にデータベースを希望する状態にして処理を完了します。

. [ バックアップするデータベース、表領域、またはデータファイル ] ページで、次の手順を実行します。
+
.. [ * データファイルのバックアップ * ] を選択して、フル・データベース、選択したデータ・ファイル、または選択した表領域をバックアップします。
.. アーカイブ・ログ・ファイルを個別にバックアップするには '*Backup archivelogs * を選択します
.. すでにバックアップされているアクティブ・ファイル・システムからアーカイブ・ログ・ファイルを削除する場合は '*Prune archivelogs * を選択します
+

NOTE: アーカイブ・ログ・ファイルに対して Flash Recovery Area （ FRA ）が有効になっている場合、 SnapManager はアーカイブ・ログ・ファイルのプルーニングに失敗します。

.. バックアップ保護を有効にする場合は、 [ バックアップの保護 ] を選択します。
+
このオプションは、プロファイルの作成時に保護ポリシーを選択した場合にのみ有効になります。

.. Protection Manager の保護スケジュールを無視して、バックアップをセカンダリ・ストレージですぐに保護する場合は、 [* Protect Now] を選択します。
.. [ タイプ * ] ドロップダウン・リストから、作成するバックアップのタイプ（オフラインまたはオンライン）を選択します。
+
Auto を選択すると、 SnapManager はデータベースの現在の状態に基づいてバックアップを作成します。

.. [*Retention Class*] ドロップダウン・リストから ' リテンション・クラスを選択します
.. バックアップ・ファイルが破損していないことを確認するには '[Oracle DBVERIFY ユーティリティを使用してバックアップを検証する *] チェック・ボックスを選択します


. タスクの有効化ページで、バックアップ処理の前後にタスクを実行するかどうかを指定します。
. [ バックアップ操作の実行 ] ページで、情報を確認し、 [* バックアップ * ] をクリックします。
. 「 * 完了」をクリックしてウィザードを閉じます。
+
処理が失敗した場合は、 * Operation Details * をクリックして、処理が失敗した原因を確認します。


